# Copyright © 2026 Xander Chen. All rights reserved.
# Generated by Django 5.2.17 on 2026-10-02 13:46

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_music_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), accounts.models.HostValidator('Apple Music', 'music.apple.com')]),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=accounts.models.avatar_path),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='A line or two about you and the music you like.', max_length=280),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), accounts.models.HostValidator('Instagram', 'instagram.com')]),
        ),
        migrations.AddField(
            model_name='user',
            name='soundcloud_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), accounts.models.HostValidator('SoundCloud', 'soundcloud.com')]),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https']), accounts.models.HostValidator('Spotify', 'spotify.com')]),
        ),
    ]
