"""Representative songs for every genre category and subgenre tag (data for seed_genre_songs).

Each entry lists where it applies: (category, None) for a broad-genre example, or (category, tag) for the
subgenre it represents. Links go to uploads on YouTube (artist, label, promoter or broadcaster channels
where possible); where a style has few released tracks online, a short DJ set or mix is used and marked
kind "set". Gathered and verified October 1, 2026; see DJ_SOURCES.md.
"""

SONGS = [
    {"title": "Superman", "artist": "Black Coffee", "url": "https://www.youtube.com/watch?v=w6-tR3PKCHA", "kind": "track",
     "where": [("Afro Electronic", None)]},
    {"title": "Tanzania", "artist": "Uncle Waffles & Tony Duardo", "url": "https://www.youtube.com/watch?v=zi7kX1jkRuA", "kind": "track",
     "where": [("Afro Electronic", None)]},
    {"title": "Water", "artist": "Tyla", "url": "https://www.youtube.com/watch?v=XoiOOiuH8iI", "kind": "track",
     "where": [("Afro Electronic", None)]},
    {"title": "An Ending (Ascent)", "artist": "Brian Eno", "url": "https://www.youtube.com/watch?v=OlaTeXX3uH8", "kind": "track",
     "where": [("Ambient / Experimental", None)]},
    {"title": "Xtal", "artist": "Aphex Twin", "url": "https://www.youtube.com/watch?v=uXpKC8TIAxE", "kind": "track",
     "where": [("Ambient / Experimental", None)]},
    {"title": "Roygbiv", "artist": "Boards of Canada", "url": "https://www.youtube.com/watch?v=SM4tQcUt_mQ", "kind": "track",
     "where": [("Ambient / Experimental", None)]},
    {"title": "Good Lies", "artist": "Overmono", "url": "https://www.youtube.com/watch?v=_EKC7JLBaJ8", "kind": "track",
     "where": [("Bass / Club", None)]},
    {"title": "Hyph Mngo", "artist": "Joy Orbison", "url": "https://www.youtube.com/watch?v=Aa_PDKKc2_A", "kind": "track",
     "where": [("Bass / Club", None)]},
    {"title": "Rumble", "artist": "Skrillex, Fred again.. & Flowdan", "url": "https://www.youtube.com/watch?v=7z25ZZ3DHds", "kind": "track",
     "where": [("Bass / Club", None)]},
    {"title": "Vai Malandra", "artist": "Anitta, MC Zaac & Maejor ft. Tropkillaz & DJ Yuri Martins", "url": "https://www.youtube.com/watch?v=kDhptBT_-VI", "kind": "track",
     "where": [("Brazilian Funk", None)]},
    {"title": "Olha a Explosão", "artist": "MC Kevinho", "url": "https://www.youtube.com/watch?v=3yd_eoMOvqk", "kind": "track",
     "where": [("Brazilian Funk", None)]},
    {"title": "Rainha da Favela", "artist": "Ludmilla", "url": "https://www.youtube.com/watch?v=DWH349RfD7E", "kind": "track",
     "where": [("Brazilian Funk", None)]},
    {"title": "Block Rockin' Beats", "artist": "The Chemical Brothers", "url": "https://www.youtube.com/watch?v=iTxOKsyZ0Lw", "kind": "track",
     "where": [("Breaks / Breakbeat", None)]},
    {"title": "Praise You", "artist": "Fatboy Slim", "url": "https://www.youtube.com/watch?v=ruAi4VBoBSM", "kind": "track",
     "where": [("Breaks / Breakbeat", None)]},
    {"title": "Firestarter", "artist": "The Prodigy", "url": "https://www.youtube.com/watch?v=wmin5WkOuPw", "kind": "track",
     "where": [("Breaks / Breakbeat", None)]},
    {"title": "Levitating", "artist": "Dua Lipa", "url": "https://www.youtube.com/watch?v=TUVcZfQe-Kw", "kind": "track",
     "where": [("Dance / Pop", None)]},
    {"title": "Feel So Close", "artist": "Calvin Harris", "url": "https://www.youtube.com/watch?v=dGghkjpNCQ8", "kind": "track",
     "where": [("Dance / Pop", None)]},
    {"title": "Titanium", "artist": "David Guetta ft. Sia", "url": "https://www.youtube.com/watch?v=JRfuAukYTKg", "kind": "track",
     "where": [("Dance / Pop", None)]},
    {"title": "Heartbeat Loud", "artist": "Andy C", "url": "https://www.youtube.com/watch?v=qc9LviBeJ6o", "kind": "track",
     "where": [("Drum & Bass", None)]},
    {"title": "Rock It", "artist": "Sub Focus", "url": "https://www.youtube.com/watch?v=k_jOkWf1lRg", "kind": "track",
     "where": [("Drum & Bass", None)]},
    {"title": "Eastern Jam", "artist": "Chase & Status", "url": "https://www.youtube.com/watch?v=Ku3bMyiINxc", "kind": "track",
     "where": [("Drum & Bass", None)]},
    {"title": "Midnight Request Line", "artist": "Skream", "url": "https://www.youtube.com/watch?v=lcMAbnZy8l8", "kind": "track",
     "where": [("Dubstep / 140", None)]},
    {"title": "Night", "artist": "Benga & Coki", "url": "https://www.youtube.com/watch?v=rNStVlJWy88", "kind": "track",
     "where": [("Dubstep / 140", None)]},
    {"title": "Scary Monsters and Nice Sprites", "artist": "Skrillex", "url": "https://www.youtube.com/watch?v=WSeNSzJ2-Jw", "kind": "track",
     "where": [("Dubstep / 140", None)]},
    {"title": "Planet Rock", "artist": "Afrika Bambaataa", "url": "https://www.youtube.com/watch?v=SqS8X-5aIns", "kind": "track",
     "where": [("Electro", None)]},
    {"title": "Numbers", "artist": "Kraftwerk", "url": "https://www.youtube.com/watch?v=jSsj3fTHtps", "kind": "track",
     "where": [("Electro", None)]},
    {"title": "Bubble Metropolis", "artist": "Drexciya", "url": "https://www.youtube.com/watch?v=5k6wmU8kTg4", "kind": "track",
     "where": [("Electro", None)]},
    {"title": "Dragonborn", "artist": "Headhunterz", "url": "https://www.youtube.com/watch?v=VaiHTvifGt0", "kind": "track",
     "where": [("Hard Dance / Hardcore", None)]},
    {"title": "Hyper Hyper", "artist": "Scooter", "url": "https://www.youtube.com/watch?v=7Twnmhe948A", "kind": "track",
     "where": [("Hard Dance / Hardcore", None)]},
    {"title": "Year of Summer", "artist": "Wildstylez ft. Niels Geusebroek", "url": "https://www.youtube.com/watch?v=WA0t6ErCtus", "kind": "track",
     "where": [("Hard Dance / Hardcore", None)]},
    {"title": "Daydream", "artist": "I Hate Models", "url": "https://www.youtube.com/watch?v=U6EjUIefwiw", "kind": "track",
     "where": [("Hard Techno", None)]},
    {"title": "Gipsy Queen", "artist": "Indira Paganotto", "url": "https://www.youtube.com/watch?v=ao6wgygaGPU", "kind": "track",
     "where": [("Hard Techno", None)]},
    {"title": "World on Fire", "artist": "Angerfist x Reinier Zonneveld", "url": "https://www.youtube.com/watch?v=1Jeewsr4ptc", "kind": "track",
     "where": [("Hard Techno", None)]},
    {"title": "Your Love", "artist": "Frankie Knuckles", "url": "https://www.youtube.com/watch?v=ottFhv0zD_8", "kind": "track",
     "where": [("House", None)]},
    {"title": "Good Life", "artist": "Inner City", "url": "https://www.youtube.com/watch?v=KJxJxr9RlKM", "kind": "track",
     "where": [("House", None)]},
    {"title": "Move Your Body", "artist": "Marshall Jefferson x Solardo", "url": "https://www.youtube.com/watch?v=yFdbueklpwY", "kind": "track",
     "where": [("House", None)]},
    {"title": "Over and Over", "artist": "Hot Chip", "url": "https://www.youtube.com/watch?v=pDJKgi2e-Aw", "kind": "track",
     "where": [("Indie Dance", None)]},
    {"title": "Lights & Music", "artist": "Cut Copy", "url": "https://www.youtube.com/watch?v=8R1X2TxW5Rk", "kind": "track",
     "where": [("Indie Dance", None)]},
    {"title": "The Look", "artist": "Metronomy", "url": "https://www.youtube.com/watch?v=sFrNsSnk8GM", "kind": "track",
     "where": [("Indie Dance", None)]},
    {"title": "Closer", "artist": "Nine Inch Nails", "url": "https://www.youtube.com/watch?v=PTFwQP86BRs", "kind": "track",
     "where": [("Industrial / EBM", None)]},
    {"title": "Headhunter", "artist": "Front 242", "url": "https://www.youtube.com/watch?v=wXLyAzgX-ho", "kind": "track",
     "where": [("Industrial / EBM", None)]},
    {"title": "Dig It", "artist": "Skinny Puppy", "url": "https://www.youtube.com/watch?v=CDKkRSUrTd8", "kind": "track",
     "where": [("Industrial / EBM", None)]},
    {"title": "Soy Yo", "artist": "Bomba Estéreo", "url": "https://www.youtube.com/watch?v=bxWxXncl53U", "kind": "track",
     "where": [("Latin Electronic", None)]},
    {"title": "Mi Gente", "artist": "J Balvin & Willy William", "url": "https://www.youtube.com/watch?v=wnJ6LuUFpMo", "kind": "track",
     "where": [("Latin Electronic", None)]},
    {"title": "Taki Taki", "artist": "DJ Snake ft. Selena Gomez, Ozuna & Cardi B", "url": "https://www.youtube.com/watch?v=ixkoVwKQaJg", "kind": "track",
     "where": [("Latin Electronic", None)]},
    {"title": "Animals", "artist": "Martin Garrix", "url": "https://www.youtube.com/watch?v=DuFUtL8zUAk", "kind": "track",
     "where": [("Mainstage / Commercial EDM", None)]},
    {"title": "Don't You Worry Child", "artist": "Swedish House Mafia ft. John Martin", "url": "https://www.youtube.com/watch?v=1y6smkh6c-0", "kind": "track",
     "where": [("Mainstage / Commercial EDM", None), ("Dance / Pop", "Commercial Electronic Crossover")]},
    {"title": "Spaceman", "artist": "Hardwell", "url": "https://www.youtube.com/watch?v=lETmskoqh30", "kind": "track",
     "where": [("Mainstage / Commercial EDM", None)]},
    {"title": "I Feel Love", "artist": "Donna Summer", "url": "https://www.youtube.com/watch?v=yEbaeLv-aOo", "kind": "track",
     "where": [("Nu Disco / Disco", None)]},
    {"title": "Get Lucky", "artist": "Daft Punk ft. Pharrell Williams & Nile Rodgers", "url": "https://www.youtube.com/watch?v=5NV6Rdv1a3I", "kind": "track",
     "where": [("Nu Disco / Disco", None)]},
    {"title": "Inspector Norse", "artist": "Todd Terje", "url": "https://www.youtube.com/watch?v=ebjXsc0UjdQ", "kind": "track",
     "where": [("Nu Disco / Disco", None), ("Indie Dance", "Cosmic Dance")]},
    {"title": "Deep Jungle Walk", "artist": "Astrix", "url": "https://www.youtube.com/watch?v=lIuEuJvKos4", "kind": "track",
     "where": [("Psy-Trance", None)]},
    {"title": "Great Spirit", "artist": "Armin van Buuren vs Vini Vici", "url": "https://www.youtube.com/watch?v=yo4pmauhugo", "kind": "track",
     "where": [("Psy-Trance", None)]},
    {"title": "Heavyweight", "artist": "Infected Mushroom", "url": "https://www.youtube.com/watch?v=EQP9DoQGJto", "kind": "track",
     "where": [("Psy-Trance", None)]},
    {"title": "Energy Flash", "artist": "Joey Beltram", "url": "https://www.youtube.com/watch?v=uFdU_aGf9rY", "kind": "track",
     "where": [("Techno", None)]},
    {"title": "Jaguar", "artist": "Underground Resistance", "url": "https://www.youtube.com/watch?v=kYRi1FzNqdc", "kind": "track",
     "where": [("Techno", None)]},
    {"title": "Doppler", "artist": "Charlotte de Witte", "url": "https://www.youtube.com/watch?v=AS8Q_5knkrg", "kind": "track",
     "where": [("Techno", None)]},
    {"title": "Children", "artist": "Robert Miles", "url": "https://www.youtube.com/watch?v=CC5ca6Hsb2Q", "kind": "track",
     "where": [("Trance", None)]},
    {"title": "Punk", "artist": "Ferry Corsten", "url": "https://www.youtube.com/watch?v=-4iJ8aCH_oc", "kind": "track",
     "where": [("Trance", None)]},
    {"title": "Blah Blah Blah", "artist": "Armin van Buuren", "url": "https://www.youtube.com/watch?v=_oprI_WcUys", "kind": "track",
     "where": [("Trance", None)]},
    {"title": "Never Be Like You", "artist": "Flume ft. Kai", "url": "https://www.youtube.com/watch?v=Ly7uj0JwgKg", "kind": "track",
     "where": [("Trap / Future Bass", None)]},
    {"title": "Core", "artist": "RL Grime", "url": "https://www.youtube.com/watch?v=04ufimjXEbA", "kind": "track",
     "where": [("Trap / Future Bass", None)]},
    {"title": "Harlem Shake", "artist": "Baauer", "url": "https://www.youtube.com/watch?v=hQNjcOdHHmA", "kind": "track",
     "where": [("Trap / Future Bass", None)]},
    {"title": "Re-Rewind (The Crowd Say Bo Selecta)", "artist": "Artful Dodger ft. Craig David", "url": "https://www.youtube.com/watch?v=M0wv_cQv8As", "kind": "track",
     "where": [("UK Garage / Bassline", None)]},
    {"title": "Sincere", "artist": "MJ Cole ft. Jay Dee & Nova Caspar", "url": "https://www.youtube.com/watch?v=DXCtYUtjDYU", "kind": "track",
     "where": [("UK Garage / Bassline", None)]},
    {"title": "Flowers", "artist": "Sweet Female Attitude", "url": "https://www.youtube.com/watch?v=iR2tIyj8_y8", "kind": "track",
     "where": [("UK Garage / Bassline", None)]},
    {"title": "Sohlala Sisonke", "artist": "Dlala Thukzin", "url": "https://www.youtube.com/watch?v=XkOhhsIH5SY", "kind": "track",
     "where": [("Afro Electronic", "3Step")]},
    {"title": "Step by Step", "artist": "Scotts Maphuma & Bob Mabena ft. QuayR Musiq", "url": "https://www.youtube.com/watch?v=HXja3g6VY7g", "kind": "track",
     "where": [("Afro Electronic", "3Step")]},
    {"title": "We Dance Again", "artist": "Black Coffee", "url": "https://www.youtube.com/watch?v=JjWaET5AWCw", "kind": "track",
     "where": [("House", "Afro House"), ("Afro Electronic", "Afro House")]},
    {"title": "Move", "artist": "Adam Port, Stryv, Keinemusik, Orso & Malachiii", "url": "https://www.youtube.com/watch?v=TVZ2YbFKT6M", "kind": "track",
     "where": [("House", "Afro House"), ("Afro Electronic", "Afro House")]},
    {"title": "Come With Me", "artist": "Black Coffee ft. Mque", "url": "https://www.youtube.com/watch?v=osQUJTBGCMs", "kind": "track",
     "where": [("Afro Electronic", "Afro Melodic")]},
    {"title": "Calm Down", "artist": "Rema", "url": "https://www.youtube.com/watch?v=CQLsdm1ZYAw", "kind": "track",
     "where": [("Dance / Pop", "Afro Pop"), ("Afro Electronic", "Afro Pop")]},
    {"title": "Rush", "artist": "Ayra Starr", "url": "https://www.youtube.com/watch?v=crtQSTYWtqE", "kind": "track",
     "where": [("Dance / Pop", "Afro Pop"), ("Afro Electronic", "Afro Pop")]},
    {"title": "The Rapture Pt.III", "artist": "&ME & Black Coffee", "url": "https://www.youtube.com/watch?v=MOenJHdj8ro", "kind": "track",
     "where": [("House", "Afro Tech"), ("Techno", "Afro Tech"), ("Afro Electronic", "Afro Tech")]},
    {"title": "Last Last", "artist": "Burna Boy", "url": "https://www.youtube.com/watch?v=421w1j87fEM", "kind": "track",
     "where": [("Afro Electronic", "Afrobeats")]},
    {"title": "Essence", "artist": "Wizkid ft. Tems", "url": "https://www.youtube.com/watch?v=jipQpjUA_o8", "kind": "track",
     "where": [("Afro Electronic", "Afrobeats")]},
    {"title": "Amapiano", "artist": "Asake & Olamide", "url": "https://www.youtube.com/watch?v=l_-v1fNdSHs", "kind": "track",
     "where": [("Afro Electronic", "Afropiano")]},
    {"title": "Unavailable", "artist": "Davido ft. Musa Keys", "url": "https://www.youtube.com/watch?v=OSBan_sH_b8", "kind": "track",
     "where": [("Afro Electronic", "Afropiano")]},
    {"title": "Ke Star", "artist": "Focalistic ft. Vigro Deep", "url": "https://www.youtube.com/watch?v=a9_da2P5JjQ", "kind": "track",
     "where": [("Afro Electronic", "Amapiano")]},
    {"title": "Bacardi via Sgidongo", "artist": "Luudadeejay ft. Kabza De Small & Mac Breezy", "url": "https://www.youtube.com/watch?v=8IeP2SnkRSc", "kind": "track",
     "where": [("Afro Electronic", "Bacardi")]},
    {"title": "Barcadi", "artist": "Chester Houseprince ft. DJ Spuzza & Mega", "url": "https://www.youtube.com/watch?v=Ai40XhvMT2o", "kind": "track",
     "where": [("Afro Electronic", "Bacardi")]},
    {"title": "Omunye", "artist": "Distruction Boyz", "url": "https://www.youtube.com/watch?v=26-dVJa5Ejc", "kind": "track",
     "where": [("Bass / Club", "Gqom"), ("Afro Electronic", "Gqom")]},
    {"title": "Quantum", "artist": "Dladla Mshunqisi", "url": "https://www.youtube.com/watch?v=0zcJj0RQ4t0", "kind": "track",
     "where": [("Afro Electronic", "Quantum")]},
    {"title": "Quantum Sound", "artist": "Hluriey ft. Jay Nox", "url": "https://www.youtube.com/watch?v=Y-TGrLyCrrc", "kind": "track",
     "where": [("Afro Electronic", "Quantum")]},
    {"title": "Hangover (BaBaBa)", "artist": "Buraka Som Sistema", "url": "https://www.youtube.com/watch?v=mQEfsMAxhAE", "kind": "track",
     "where": [("Afro Electronic", "Related African Electronic / Club Styles")]},
    {"title": "Don't Bother They're Here", "artist": "Stars of the Lid", "url": "https://www.youtube.com/watch?v=_DsYk-WM5Rk", "kind": "track",
     "where": [("Ambient / Experimental", "Ambient"), ("Ambient / Experimental", "Drone")]},
    {"title": "Little Fluffy Clouds", "artist": "The Orb", "url": "https://www.youtube.com/watch?v=KNfjpmvbQG0", "kind": "track",
     "where": [("Ambient / Experimental", "Ambient House")]},
    {"title": "Papua New Guinea", "artist": "The Future Sound of London", "url": "https://www.youtube.com/watch?v=6QCXpHdW9ak", "kind": "track",
     "where": [("Ambient / Experimental", "Ambient House")]},
    {"title": "Hall of Mirrors", "artist": "B12", "url": "https://www.youtube.com/watch?v=EwHIBf1mGJg", "kind": "track",
     "where": [("Ambient / Experimental", "Ambient Techno")]},
    {"title": "Novelty Waves", "artist": "Biosphere", "url": "https://www.youtube.com/watch?v=p2Rcv5_pRhk", "kind": "track",
     "where": [("Ambient / Experimental", "Ambient Techno")]},
    {"title": "Windowlicker", "artist": "Aphex Twin", "url": "https://www.youtube.com/watch?v=5ZT3gTu4Sjw", "kind": "track",
     "where": [("Ambient / Experimental", "Braindance")]},
    {"title": "My Red Hot Car", "artist": "Squarepusher", "url": "https://www.youtube.com/watch?v=v8PvoUkcjE4", "kind": "track",
     "where": [("Ambient / Experimental", "Braindance")]},
    {"title": "In the Waiting Line", "artist": "Zero 7", "url": "https://www.youtube.com/watch?v=Jj6yXxVc21Y", "kind": "track",
     "where": [("Ambient / Experimental", "Chillout")]},
    {"title": "Lebanese Blonde", "artist": "Thievery Corporation", "url": "https://www.youtube.com/watch?v=1t7W6NtTKAw", "kind": "track",
     "where": [("Ambient / Experimental", "Chillout")]},
    {"title": "Teardrop", "artist": "Massive Attack", "url": "https://www.youtube.com/watch?v=u7K72X4eo_s", "kind": "track",
     "where": [("Ambient / Experimental", "Downtempo")]},
    {"title": "Kerala", "artist": "Bonobo", "url": "https://www.youtube.com/watch?v=S0Q4gqBUs7c", "kind": "track",
     "where": [("Ambient / Experimental", "Downtempo")]},
    {"title": "Angel Echoes", "artist": "Four Tet", "url": "https://www.youtube.com/watch?v=FiBBcHZ84i8", "kind": "track",
     "where": [("Ambient / Experimental", "Electronica")]},
    {"title": "A New Error", "artist": "Moderat", "url": "https://www.youtube.com/watch?v=QpxFcMYRV08", "kind": "track",
     "where": [("Ambient / Experimental", "Electronica")]},
    {"title": "Gantz Graf", "artist": "Autechre", "url": "https://www.youtube.com/watch?v=xNRPl0kA0a4", "kind": "track",
     "where": [("Ambient / Experimental", "Experimental Electronic")]},
    {"title": "Sleep Dealer", "artist": "Oneohtrix Point Never", "url": "https://www.youtube.com/watch?v=5DGRc1qn86o", "kind": "track",
     "where": [("Ambient / Experimental", "Experimental Electronic")]},
    {"title": "Do While", "artist": "Oval", "url": "https://www.youtube.com/watch?v=RYSTR9bA9wQ", "kind": "track",
     "where": [("Ambient / Experimental", "Glitch")]},
    {"title": "Xerrox Monophaser", "artist": "Alva Noto", "url": "https://www.youtube.com/watch?v=xbdwnEc3EcE", "kind": "track",
     "where": [("Ambient / Experimental", "Glitch")]},
    {"title": "Bike", "artist": "Autechre", "url": "https://www.youtube.com/watch?v=qkTJTf7Yvk8", "kind": "track",
     "where": [("Ambient / Experimental", "IDM")]},
    {"title": "Open Eye Signal", "artist": "Jon Hopkins", "url": "https://www.youtube.com/watch?v=I1gbdckhOKw", "kind": "track",
     "where": [("Ambient / Experimental", "Leftfield Electronica")]},
    {"title": "Can't Do Without You", "artist": "Caribou", "url": "https://www.youtube.com/watch?v=BI2Et19vDCM", "kind": "track",
     "where": [("Ambient / Experimental", "Leftfield Electronica"), ("Indie Dance", "Electronic Indie")]},
    {"title": "Endless Summer", "artist": "Fennesz", "url": "https://www.youtube.com/watch?v=pzieKZ2OO-E", "kind": "track",
     "where": [("Ambient / Experimental", "Microsound")]},
    {"title": "data.matrix", "artist": "Ryoji Ikeda", "url": "https://www.youtube.com/watch?v=JZcMLjnm1ps", "kind": "track",
     "where": [("Ambient / Experimental", "Microsound")]},
    {"title": "Dance My Pain Away", "artist": "Rod Lee", "url": "https://www.youtube.com/watch?v=quUSjngSmN0", "kind": "track",
     "where": [("Bass / Club", "Baltimore Club")]},
    {"title": "I'm the Ish", "artist": "DJ Class", "url": "https://www.youtube.com/watch?v=UMvhhRFlwIU", "kind": "track",
     "where": [("Bass / Club", "Baltimore Club")]},
    {"title": "Cockney Thug", "artist": "Rusko", "url": "https://www.youtube.com/watch?v=iNmGzWe5jC8", "kind": "track",
     "where": [("Bass / Club", "Bass Music")]},
    {"title": "Changes", "artist": "Mala", "url": "https://www.youtube.com/watch?v=fw-YeFtggF8", "kind": "track",
     "where": [("Bass / Club", "Bass Music"), ("Dubstep / 140", "140"), ("Dubstep / 140", "Deep Dubstep")]},
    {"title": "So U Kno", "artist": "Overmono", "url": "https://www.youtube.com/watch?v=SRVxRUJxITY", "kind": "track",
     "where": [("Bass / Club", "Broken Club")]},
    {"title": "Reverie", "artist": "Arca", "url": "https://www.youtube.com/watch?v=0WKWZ9y-dvU", "kind": "track",
     "where": [("Bass / Club", "Deconstructed Club")]},
    {"title": "Mequetrefe", "artist": "Arca", "url": "https://www.youtube.com/watch?v=AZKPd3k6O6A", "kind": "track",
     "where": [("Bass / Club", "Deconstructed Club")]},
    {"title": "Archangel", "artist": "Burial", "url": "https://www.youtube.com/watch?v=wXQpfEFlnYU", "kind": "track",
     "where": [("Bass / Club", "Experimental Bass"), ("Dubstep / 140", "140"), ("UK Garage / Bassline", "Future Garage")]},
    {"title": "Maybes", "artist": "Mount Kimbie", "url": "https://www.youtube.com/watch?v=9hTN19x1DyM", "kind": "track",
     "where": [("Bass / Club", "Experimental Bass")]},
    {"title": "Only One", "artist": "DJ Rashad", "url": "https://www.youtube.com/watch?v=bVyclJz3oaU", "kind": "track",
     "where": [("Bass / Club", "Footwork")]},
    {"title": "Baby Come On", "artist": "RP Boo", "url": "https://www.youtube.com/watch?v=L17sHYmwTWY", "kind": "track",
     "where": [("Bass / Club", "Footwork")]},
    {"title": "Sinistro", "artist": "DJ Nigga Fox", "url": "https://www.youtube.com/watch?v=3NF0X6qFCV0", "kind": "track",
     "where": [("Bass / Club", "Global Club")]},
    {"title": "Waaba-Jah", "artist": "DJ Nigga Fox", "url": "https://www.youtube.com/watch?v=1-QCJMNk2uw", "kind": "track",
     "where": [("Bass / Club", "Global Club")]},
    {"title": "Boiler Room London: Bass & Percs Special", "artist": "Sherelle", "url": "https://www.youtube.com/watch?v=Z4_KD9UhdCE", "kind": "set",
     "where": [("Bass / Club", "Hard Drum")]},
    {"title": "Boiler Room London: Bass & Percs Special", "artist": "Jossy Mitsu", "url": "https://www.youtube.com/watch?v=-2RBDJ95WTs", "kind": "set",
     "where": [("Bass / Club", "Hard Drum")]},
    {"title": "When We Get Freaky", "artist": "UNIIQU3 x DJ Bake", "url": "https://www.youtube.com/watch?v=XxBvM6dmS8Q", "kind": "track",
     "where": [("Bass / Club", "Jersey Club")]},
    {"title": "All That Matters", "artist": "Salako", "url": "https://www.youtube.com/watch?v=U23aYsGsVps", "kind": "track",
     "where": [("Bass / Club", "Jersey Club")]},
    {"title": "Let U No", "artist": "DJ Rashad", "url": "https://www.youtube.com/watch?v=F81MGI5Igsg", "kind": "track",
     "where": [("Bass / Club", "Juke")]},
    {"title": "Chimes", "artist": "Hudson Mohawke", "url": "https://www.youtube.com/watch?v=k_MWuP2Qj7U", "kind": "track",
     "where": [("Bass / Club", "Leftfield Bass")]},
    {"title": "Anti War Dub", "artist": "Mala", "url": "https://www.youtube.com/watch?v=--jr22La8Nk", "kind": "track",
     "where": [("Bass / Club", "Leftfield Bass")]},
    {"title": "Idiot", "artist": "Ikonika", "url": "https://www.youtube.com/watch?v=w3WgtCT3N0c", "kind": "track",
     "where": [("Bass / Club", "UK Bass")]},
    {"title": "Squark", "artist": "Roska", "url": "https://www.youtube.com/watch?v=Hf_DTjaY7E4", "kind": "track",
     "where": [("UK Garage / Bassline", "UK Funky"), ("Bass / Club", "UK Funky")]},
    {"title": "Love Dub", "artist": "Cooly G", "url": "https://www.youtube.com/watch?v=me52KU8UawE", "kind": "track",
     "where": [("UK Garage / Bassline", "UK Funky"), ("Bass / Club", "UK Funky")]},
    {"title": "Mega Automotivo Sem Sinal", "artist": "DJ GBR, Guuga, MC Baroni & MC Yago", "url": "https://www.youtube.com/watch?v=A4gpzJwOM6o", "kind": "track",
     "where": [("Brazilian Funk", "Automotivo")]},
    {"title": "Vem Quebrando", "artist": "MC Danone", "url": "https://www.youtube.com/watch?v=vqKsHbyjjjI", "kind": "track",
     "where": [("Brazilian Funk", "BH Funk")]},
    {"title": "Maldita de Ex", "artist": "MC Leozin", "url": "https://www.youtube.com/watch?v=RcL402OTE4U", "kind": "track",
     "where": [("Brazilian Funk", "BH Funk")]},
    {"title": "Solta o Frango", "artist": "Bonde do Rolê", "url": "https://www.youtube.com/watch?v=Kgb6FxuaPQA", "kind": "track",
     "where": [("Brazilian Funk", "Baile Funk")]},
    {"title": "Toca na Pista", "artist": "Tropkillaz & Heavy Baile ft. MC Carol", "url": "https://www.youtube.com/watch?v=H9I7L8aApAc", "kind": "track",
     "where": [("Brazilian Funk", "Baile Funk")]},
    {"title": "Fazer Falta", "artist": "MC Livinho", "url": "https://www.youtube.com/watch?v=bUeuvDCrqr0", "kind": "track",
     "where": [("Brazilian Funk", "Brazilian Funk"), ("Brazilian Funk", "Melodic Funk")]},
    {"title": "Fuego", "artist": "Alok & Bhaskar", "url": "https://www.youtube.com/watch?v=VQ2EyU75p2o", "kind": "track",
     "where": [("Brazilian Funk", "Eletrofunk")]},
    {"title": "Tina", "artist": "Vintage Culture, Bhaskar & Meca ft. The Vic", "url": "https://www.youtube.com/watch?v=LQkrsm9xVxg", "kind": "track",
     "where": [("Brazilian Funk", "Eletrofunk")]},
    {"title": "Rap das Armas", "artist": "Cidinho & Doca", "url": "https://www.youtube.com/watch?v=Rj-Q-cgG70I", "kind": "track",
     "where": [("Brazilian Funk", "Favela Funk")]},
    {"title": "Glamurosa", "artist": "MC Marcinho", "url": "https://www.youtube.com/watch?v=am3U2a_wpV4", "kind": "track",
     "where": [("Brazilian Funk", "Favela Funk"), ("Brazilian Funk", "Funk Carioca")]},
    {"title": "Boladona", "artist": "Tati Quebra Barraco", "url": "https://www.youtube.com/watch?v=USO_Dfu-6Yg", "kind": "track",
     "where": [("Brazilian Funk", "Funk Carioca")]},
    {"title": "Só Mandela", "artist": "MC Ryan SP & MC GW", "url": "https://www.youtube.com/watch?v=eODylWQP3-M", "kind": "track",
     "where": [("Brazilian Funk", "Mandelão Funk")]},
    {"title": "Na Treta Grita Meu Vulgo", "artist": "DJ GBR, MC GW & MC Paiva", "url": "https://www.youtube.com/watch?v=j-OlsvrsGg4", "kind": "track",
     "where": [("Brazilian Funk", "Mandelão Funk")]},
    {"title": "My Name Isn't Johnny", "artist": "MC Maromba", "url": "https://www.youtube.com/watch?v=pPe2rsjkwM0", "kind": "track",
     "where": [("Brazilian Funk", "Rasteirinha")]},
    {"title": "Finished Symphony", "artist": "Hybrid", "url": "https://www.youtube.com/watch?v=60OR68EfvS8", "kind": "track",
     "where": [("Breaks / Breakbeat", "Acid Breaks"), ("Breaks / Breakbeat", "Progressive Breaks")]},
    {"title": "If I Survive", "artist": "Hybrid", "url": "https://www.youtube.com/watch?v=WbOW2H9sBnk", "kind": "track",
     "where": [("Breaks / Breakbeat", "Acid Breaks")]},
    {"title": "Hey Boy Hey Girl", "artist": "The Chemical Brothers", "url": "https://www.youtube.com/watch?v=tpKCqp9CALQ", "kind": "track",
     "where": [("Breaks / Breakbeat", "Big Beat")]},
    {"title": "The Rockafeller Skank", "artist": "Fatboy Slim", "url": "https://www.youtube.com/watch?v=FMrIy9zm7QY", "kind": "track",
     "where": [("Breaks / Breakbeat", "Big Beat")]},
    {"title": "Out of Space", "artist": "The Prodigy", "url": "https://www.youtube.com/watch?v=a4eav7dFvc8", "kind": "track",
     "where": [("Breaks / Breakbeat", "Breakbeat")]},
    {"title": "Push Up", "artist": "The Freestylers", "url": "https://www.youtube.com/watch?v=VU01OK3EKvw", "kind": "track",
     "where": [("Breaks / Breakbeat", "Breakbeat")]},
    {"title": "We Want Your Soul", "artist": "Adam Freeland", "url": "https://www.youtube.com/watch?v=0oMEuyhBkRo", "kind": "track",
     "where": [("Breaks / Breakbeat", "Breaks")]},
    {"title": "Mind Killer", "artist": "Adam Freeland", "url": "https://www.youtube.com/watch?v=m2QFg-8TEMg", "kind": "track",
     "where": [("Breaks / Breakbeat", "Electro Breaks"), ("Electro", "Electro Breaks")]},
    {"title": "Da Antidote", "artist": "Stanton Warriors", "url": "https://www.youtube.com/watch?v=p8QEMNgiwfY", "kind": "track",
     "where": [("Breaks / Breakbeat", "Electro Breaks"), ("Electro", "Electro Breaks"), ("Breaks / Breakbeat", "Nu-Skool Breaks")]},
    {"title": "History Repeating", "artist": "The Propellerheads", "url": "https://www.youtube.com/watch?v=cbUO2N2Stpo", "kind": "track",
     "where": [("Breaks / Breakbeat", "Funky Breaks")]},
    {"title": "Weapon of Choice", "artist": "Fatboy Slim", "url": "https://www.youtube.com/watch?v=wCDIYvFmgW8", "kind": "track",
     "where": [("Breaks / Breakbeat", "Funky Breaks")]},
    {"title": "Finally Moving", "artist": "Pretty Lights", "url": "https://www.youtube.com/watch?v=ASpA9Zd2Z0o", "kind": "track",
     "where": [("Breaks / Breakbeat", "Glitch Hop")]},
    {"title": "Drive It Like You Stole It", "artist": "The Glitch Mob", "url": "https://www.youtube.com/watch?v=hEUs9rwNFcs", "kind": "track",
     "where": [("Breaks / Breakbeat", "Glitch Hop")]},
    {"title": "Flaming June", "artist": "BT", "url": "https://www.youtube.com/watch?v=YaOc4W_OyM0", "kind": "track",
     "where": [("Breaks / Breakbeat", "Progressive Breaks")]},
    {"title": "Don't Start Now", "artist": "Dua Lipa", "url": "https://www.youtube.com/watch?v=oygrmJFKYZY", "kind": "track",
     "where": [("Dance / Pop", "Dance-Pop")]},
    {"title": "Can't Get You Out of My Head", "artist": "Kylie Minogue", "url": "https://www.youtube.com/watch?v=c18441Eh_WE", "kind": "track",
     "where": [("Dance / Pop", "Dance-Pop")]},
    {"title": "Closer", "artist": "The Chainsmokers ft. Halsey", "url": "https://www.youtube.com/watch?v=PT2_F-1esPk", "kind": "track",
     "where": [("Dance / Pop", "EDM-Pop")]},
    {"title": "Clarity", "artist": "Zedd ft. Foxes", "url": "https://www.youtube.com/watch?v=IxxstCcJlsc", "kind": "track",
     "where": [("Dance / Pop", "EDM-Pop")]},
    {"title": "Dancing On My Own", "artist": "Robyn", "url": "https://www.youtube.com/watch?v=CcNo07Xp8aQ", "kind": "track",
     "where": [("Dance / Pop", "Electropop")]},
    {"title": "The Mother We Share", "artist": "Chvrches", "url": "https://www.youtube.com/watch?v=_mTRvJ9fugM", "kind": "track",
     "where": [("Dance / Pop", "Electropop")]},
    {"title": "What Is Love", "artist": "Haddaway", "url": "https://www.youtube.com/watch?v=xCwAriSmaFI", "kind": "track",
     "where": [("Dance / Pop", "Eurodance")]},
    {"title": "Rhythm Is a Dancer", "artist": "Snap!", "url": "https://www.youtube.com/watch?v=JYIaWeVL1JM", "kind": "track",
     "where": [("Dance / Pop", "Eurodance")]},
    {"title": "Firestone", "artist": "Kygo ft. Conrad Sewell", "url": "https://www.youtube.com/watch?v=9Sc-ir2UwGU", "kind": "track",
     "where": [("House", "Tropical House"), ("Dance / Pop", "Tropical House")]},
    {"title": "Are You with Me", "artist": "Lost Frequencies", "url": "https://www.youtube.com/watch?v=VjHMDlAPMUw", "kind": "track",
     "where": [("House", "Tropical House"), ("Dance / Pop", "Tropical House")]},
    {"title": "Wake Me Up", "artist": "Avicii", "url": "https://www.youtube.com/watch?v=IcrbM1l_BoI", "kind": "track",
     "where": [("Dance / Pop", "Commercial Electronic Crossover"), ("Mainstage / Commercial EDM", "Commercial EDM")]},
    {"title": "Feel the Love", "artist": "Rudimental ft. John Newman", "url": "https://www.youtube.com/watch?v=oABEGc8Dus0", "kind": "track",
     "where": [("Dance / Pop", "Commercial Vocal Dance")]},
    {"title": "Rather Be", "artist": "Clean Bandit ft. Jess Glynne", "url": "https://www.youtube.com/watch?v=m-M1AtrxztU", "kind": "track",
     "where": [("Dance / Pop", "Commercial Vocal Dance")]},
    {"title": "Horizons", "artist": "LTJ Bukem", "url": "https://www.youtube.com/watch?v=omJuxrA5NhM", "kind": "track",
     "where": [("Drum & Bass", "Atmospheric DnB")]},
    {"title": "Together", "artist": "Logistics", "url": "https://www.youtube.com/watch?v=3f-XOhfDhxk", "kind": "track",
     "where": [("Drum & Bass", "Atmospheric DnB"), ("Drum & Bass", "Liquid Funk")]},
    {"title": "Afterglow", "artist": "Wilkinson", "url": "https://www.youtube.com/watch?v=I9QGpHScGug", "kind": "track",
     "where": [("Drum & Bass", "Dancefloor")]},
    {"title": "Blind Faith", "artist": "Chase & Status", "url": "https://www.youtube.com/watch?v=zYpDJw7fThU", "kind": "track",
     "where": [("Drum & Bass", "Dancefloor")]},
    {"title": "Funktion", "artist": "Ed Rush & Optical", "url": "https://www.youtube.com/watch?v=NVQIMLbVdYM", "kind": "track",
     "where": [("Drum & Bass", "Darkstep")]},
    {"title": "Even If", "artist": "Calibre", "url": "https://www.youtube.com/watch?v=j_hzoTof0E8", "kind": "track",
     "where": [("Drum & Bass", "Deep DnB")]},
    {"title": "Inner City Life", "artist": "Goldie", "url": "https://www.youtube.com/watch?v=i-P98B2skts", "kind": "track",
     "where": [("Drum & Bass", "Drum & Bass")]},
    {"title": "Brown Paper Bag", "artist": "Roni Size", "url": "https://www.youtube.com/watch?v=cwI0gbGEyuI", "kind": "track",
     "where": [("Drum & Bass", "Drum & Bass")]},
    {"title": "Forsaken", "artist": "Alix Perez ft. Peven Everett & Spectrasoul", "url": "https://www.youtube.com/watch?v=YmQgRAr8lB0", "kind": "track",
     "where": [("Drum & Bass", "Drumfunk")]},
    {"title": "Stigma", "artist": "Noisia", "url": "https://www.youtube.com/watch?v=dr4JQDBwnJk", "kind": "track",
     "where": [("Drum & Bass", "Halftime")]},
    {"title": "Machine Gun", "artist": "Noisia", "url": "https://www.youtube.com/watch?v=SAO-lzl3vVQ", "kind": "track",
     "where": [("Drum & Bass", "Halftime"), ("Drum & Bass", "Neurofunk")]},
    {"title": "Share the Fall", "artist": "Roni Size & Reprazent", "url": "https://www.youtube.com/watch?v=vhlkFEA0azk", "kind": "track",
     "where": [("Drum & Bass", "Jazz DnB")]},
    {"title": "Moving with You", "artist": "Netsky", "url": "https://www.youtube.com/watch?v=F1mUD1ouvHc", "kind": "track",
     "where": [("Drum & Bass", "Jazz DnB")]},
    {"title": "Mr Happy", "artist": "DJ Hazard & Distorted Minds", "url": "https://www.youtube.com/watch?v=PlRn5bGF_4o", "kind": "track",
     "where": [("Drum & Bass", "Jump-Up")]},
    {"title": "Original Nuttah", "artist": "Shy FX & UK Apache", "url": "https://www.youtube.com/watch?v=GclYmrvWyuY", "kind": "track",
     "where": [("Drum & Bass", "Jungle")]},
    {"title": "Roll the Beats", "artist": "DJ Hype", "url": "https://www.youtube.com/watch?v=-NTVJP6Gf4g", "kind": "track",
     "where": [("Drum & Bass", "Jungle")]},
    {"title": "If We Ever", "artist": "High Contrast", "url": "https://www.youtube.com/watch?v=Pz1W1OLkw14", "kind": "track",
     "where": [("Drum & Bass", "Liquid DnB")]},
    {"title": "Rio", "artist": "Netsky ft. Digital Farm Animals", "url": "https://www.youtube.com/watch?v=qFDP9egTwfM", "kind": "track",
     "where": [("Drum & Bass", "Liquid DnB")]},
    {"title": "Return of Forever", "artist": "High Contrast", "url": "https://www.youtube.com/watch?v=XoSscshAG-4", "kind": "track",
     "where": [("Drum & Bass", "Liquid Funk")]},
    {"title": "Mr Natural", "artist": "Calibre", "url": "https://www.youtube.com/watch?v=WWxUhHdhuWQ", "kind": "track",
     "where": [("Drum & Bass", "Minimal DnB")]},
    {"title": "Helarctos", "artist": "Nu:Tone", "url": "https://www.youtube.com/watch?v=fqo4xatb9a8", "kind": "track",
     "where": [("Drum & Bass", "Minimal DnB")]},
    {"title": "Energie", "artist": "Phace & Misanthrop", "url": "https://www.youtube.com/watch?v=xqG73sGOl8Y", "kind": "track",
     "where": [("Drum & Bass", "Neurofunk")]},
    {"title": "Freefall", "artist": "Metrik ft. Reija Lee", "url": "https://www.youtube.com/watch?v=ielnIal0694", "kind": "track",
     "where": [("Drum & Bass", "Rollers")]},
    {"title": "Give & Take", "artist": "Netsky", "url": "https://www.youtube.com/watch?v=4YeNC-CXQiQ", "kind": "track",
     "where": [("Drum & Bass", "Soulful DnB")]},
    {"title": "Sweet Harmony", "artist": "Danny Byrd ft. Liquid", "url": "https://www.youtube.com/watch?v=ZqEg0B4tn1k", "kind": "track",
     "where": [("Drum & Bass", "Soulful DnB")]},
    {"title": "Alien Girl", "artist": "Ed Rush & Optical", "url": "https://www.youtube.com/watch?v=J1eGg4s86is", "kind": "track",
     "where": [("Drum & Bass", "Techstep")]},
    {"title": "Swagga", "artist": "Excision & Datsik", "url": "https://www.youtube.com/watch?v=fphS3QKh2ZQ", "kind": "track",
     "where": [("Dubstep / 140", "Brostep")]},
    {"title": "Bass Head", "artist": "Bassnectar", "url": "https://www.youtube.com/watch?v=JRftXCiqfQ8", "kind": "track",
     "where": [("Dubstep / 140", "Brostep"), ("Dubstep / 140", "Wobble")]},
    {"title": "Anti War Dub", "artist": "Digital Mystikz", "url": "https://www.youtube.com/watch?v=G9H3i0T1iN4", "kind": "track",
     "where": [("Dubstep / 140", "Deep Dubstep")]},
    {"title": "Haunted", "artist": "Digital Mystikz", "url": "https://www.youtube.com/watch?v=ukuje1iWvV8", "kind": "track",
     "where": [("Dubstep / 140", "Dubstep")]},
    {"title": "I Luv U", "artist": "Dizzee Rascal", "url": "https://www.youtube.com/watch?v=YH0KWX2a8zY", "kind": "track",
     "where": [("Dubstep / 140", "Grime")]},
    {"title": "That's Not Me", "artist": "Skepta ft. JME", "url": "https://www.youtube.com/watch?v=_xQKWnvtg6c", "kind": "track",
     "where": [("Dubstep / 140", "Grime")]},
    {"title": "Eskimo", "artist": "Wiley", "url": "https://www.youtube.com/watch?v=_KApOw_Cx7A", "kind": "track",
     "where": [("Dubstep / 140", "Instrumental Grime")]},
    {"title": "Ice Rink", "artist": "Wiley", "url": "https://www.youtube.com/watch?v=QtXSn_mFV3A", "kind": "track",
     "where": [("Dubstep / 140", "Instrumental Grime")]},
    {"title": "Days to Come", "artist": "Seven Lions ft. Fiora", "url": "https://www.youtube.com/watch?v=uNQqqztmLYU", "kind": "track",
     "where": [("Dubstep / 140", "Melodic Dubstep"), ("Trap / Future Bass", "Melodic Bass")]},
    {"title": "Edge", "artist": "Rezz", "url": "https://www.youtube.com/watch?v=9ebn_Mw7anc", "kind": "track",
     "where": [("Dubstep / 140", "Midtempo")]},
    {"title": "Griztronics II (Another Level)", "artist": "GRiZ x Subtronics", "url": "https://www.youtube.com/watch?v=4fNk2Ya_HSA", "kind": "track",
     "where": [("Dubstep / 140", "Riddim")]},
    {"title": "Titans", "artist": "Excision & Wooli", "url": "https://www.youtube.com/watch?v=KeDF-VjEfp0", "kind": "track",
     "where": [("Dubstep / 140", "Tearout")]},
    {"title": "Asteroid", "artist": "Subtronics x Excision", "url": "https://www.youtube.com/watch?v=C3fom8thYc4", "kind": "track",
     "where": [("Dubstep / 140", "Tearout")]},
    {"title": "Marmite", "artist": "Caspa", "url": "https://www.youtube.com/watch?v=KAAPcX6vwVs", "kind": "track",
     "where": [("Dubstep / 140", "UK Dubstep")]},
    {"title": "26 Basslines", "artist": "Benga", "url": "https://www.youtube.com/watch?v=0-7A6yvc82s", "kind": "track",
     "where": [("Dubstep / 140", "UK Dubstep")]},
    {"title": "Promises", "artist": "Nero", "url": "https://www.youtube.com/watch?v=llDikI2hTtk", "kind": "track",
     "where": [("Dubstep / 140", "Wobble")]},
    {"title": "Technology", "artist": "Aux 88", "url": "https://www.youtube.com/watch?v=WuCsQm8SeqQ", "kind": "track",
     "where": [("Electro", "Acid Electro"), ("Electro", "Detroit Electro")]},
    {"title": "Disco Rout", "artist": "Legowelt", "url": "https://www.youtube.com/watch?v=ev41VNFIGg8", "kind": "track",
     "where": [("Electro", "Acid Electro")]},
    {"title": "Egypt, Egypt", "artist": "Egyptian Lover", "url": "https://www.youtube.com/watch?v=Z3vZTk7603U", "kind": "track",
     "where": [("Electro", "Electro")]},
    {"title": "Rockit", "artist": "Herbie Hancock", "url": "https://www.youtube.com/watch?v=GHhD4PD75zY", "kind": "track",
     "where": [("Electro", "Electro-Funk")]},
    {"title": "Clear", "artist": "Cybotron", "url": "https://www.youtube.com/watch?v=Unc8kDUzbU8", "kind": "track",
     "where": [("Electro", "Electro-Funk")]},
    {"title": "Stress", "artist": "Justice", "url": "https://www.youtube.com/watch?v=QWaWsgBbFsA", "kind": "track",
     "where": [("Electro", "Modern Electro")]},
    {"title": "Oi Oi Oi", "artist": "Boys Noize", "url": "https://www.youtube.com/watch?v=q6vNJXlUUCY", "kind": "track",
     "where": [("Electro", "Modern Electro")]},
    {"title": "Techno City", "artist": "Cybotron", "url": "https://www.youtube.com/watch?v=A8mrhIoQ0uw", "kind": "track",
     "where": [("Electro", "Techno-Electro")]},
    {"title": "Wavejumper", "artist": "Drexciya", "url": "https://www.youtube.com/watch?v=dyYLBYY7ipg", "kind": "track",
     "where": [("Electro", "Techno-Electro")]},
    {"title": "Hajnal", "artist": "Venetian Snares", "url": "https://www.youtube.com/watch?v=R8HsWeWZAN8", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Breakcore")]},
    {"title": "Delete Yourself!", "artist": "Atari Teenage Riot", "url": "https://www.youtube.com/watch?v=sla0FH16Wsg", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Breakcore")]},
    {"title": "Imaginary", "artist": "Brennan Heart & Jonathan Mendelsohn", "url": "https://www.youtube.com/watch?v=h9I-9Sj4sKs", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Euphoric Hardstyle")]},
    {"title": "Frenchcore Worldwide", "artist": "Dr. Peacock ft. Da Mouth of Madness", "url": "https://www.youtube.com/watch?v=cDeuKXPejw0", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Frenchcore")]},
    {"title": "Frenchcore Killah", "artist": "The Sickest Squad ft. Lenny Dee", "url": "https://www.youtube.com/watch?v=s01xUJYGWdk", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Frenchcore")]},
    {"title": "Gabber Is a Way of Life", "artist": "Rotterdam Terror Corps", "url": "https://www.youtube.com/watch?v=e7UHnrDe-2w", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Gabber")]},
    {"title": "Wonderful Days", "artist": "Charly Lownoise & Mental Theo", "url": "https://www.youtube.com/watch?v=x-yNj6onMVY", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Happy Hardcore")]},
    {"title": "Burning Up", "artist": "Tony De Vit", "url": "https://www.youtube.com/watch?v=gAhQFRLwEis", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Hard House")]},
    {"title": "Mystery Land", "artist": "Y Traxx", "url": "https://www.youtube.com/watch?v=nWV6aNY5MYE", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Hard House")]},
    {"title": "Lizard", "artist": "Mauro Picotto", "url": "https://www.youtube.com/watch?v=9zKufc8hD44", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Hard Trance"), ("Trance", "Hard Trance")]},
    {"title": "Komodo", "artist": "Mauro Picotto", "url": "https://www.youtube.com/watch?v=hem6LPHa5zQ", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Hard Trance"), ("Trance", "Hard Trance")]},
    {"title": "Criminally Insane", "artist": "Angerfist", "url": "https://www.youtube.com/watch?v=5bKLt09Wn4k", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Hardcore")]},
    {"title": "Scrap Attack", "artist": "Headhunterz", "url": "https://www.youtube.com/watch?v=CECA-36_lwc", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Hardstyle")]},
    {"title": "Lose My Mind", "artist": "Brennan Heart & Wildstylez", "url": "https://www.youtube.com/watch?v=JP6Tz5tP8EE", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Hardstyle")]},
    {"title": "Heavenly Jumpstyle", "artist": "The Vibe Guide", "url": "https://www.youtube.com/watch?v=6HJjhZ-jloI", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Jumpstyle")]},
    {"title": "Polska Jumpstyle", "artist": "Mr. Polska", "url": "https://www.youtube.com/watch?v=sAY4KVtsTUE", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Jumpstyle")]},
    {"title": "Insolent Rave", "artist": "Nico Moreno", "url": "https://www.youtube.com/watch?v=OgaU5BUChBE", "kind": "track",
     "where": [("Hard Techno", "Neo-Rave"), ("Hard Dance / Hardcore", "Neo-Rave")]},
    {"title": "Legacy", "artist": "Sara Landry", "url": "https://www.youtube.com/watch?v=xTgVgTKa2zQ", "kind": "track",
     "where": [("Hard Techno", "Neo-Rave"), ("Hard Dance / Hardcore", "Neo-Rave")]},
    {"title": "Chain Reaction (Reverze Anthem 2025)", "artist": "Rebelion", "url": "https://www.youtube.com/watch?v=EKh60G6JYLQ", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Rawstyle")]},
    {"title": "Raw Resurgence", "artist": "Rebelion & Nolz", "url": "https://www.youtube.com/watch?v=_jnqpGHi68A", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Rawstyle")]},
    {"title": "Reverse the Bass", "artist": "TNT", "url": "https://www.youtube.com/watch?v=oteAfvKjcwI", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Reverse Bass")]},
    {"title": "The Terrordome", "artist": "Drokz", "url": "https://www.youtube.com/watch?v=A_aX3oK-kzc", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Terror / Terrorcore")]},
    {"title": "Terrorcore Addict", "artist": "Sihk & Drokz", "url": "https://www.youtube.com/watch?v=EK7c_R8ID1g", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Terror / Terrorcore")]},
    {"title": "Anybody Else but You", "artist": "Dougal & Gammer", "url": "https://www.youtube.com/watch?v=ZNUNzz61ffI", "kind": "track",
     "where": [("Hard Dance / Hardcore", "UK Hardcore")]},
    {"title": "Wanting to Get High", "artist": "Hixxy & Sharkey", "url": "https://www.youtube.com/watch?v=jT2iEvitYk4", "kind": "track",
     "where": [("Hard Dance / Hardcore", "UK Hardcore")]},
    {"title": "Mijn zoon denkt dat hij een kikker is", "artist": "Sefa", "url": "https://www.youtube.com/watch?v=lLCj78BKL2g", "kind": "track",
     "where": [("Hard Dance / Hardcore", "Uptempo")]},
    {"title": "Acid Ascention (Club Mix)", "artist": "Dax J", "url": "https://www.youtube.com/watch?v=VcDBxBnn4z0", "kind": "track",
     "where": [("Hard Techno", "Acid Hard Techno")]},
    {"title": "Overdrive", "artist": "Charlotte de Witte", "url": "https://www.youtube.com/watch?v=u1v-TN6j0Rk", "kind": "track",
     "where": [("Hard Techno", "Hard Techno")]},
    {"title": "Arriba", "artist": "2HOT2PLAY", "url": "https://www.youtube.com/watch?v=S81LZ01UlNI", "kind": "track",
     "where": [("Hard Techno", "Hard-Bounce")]},
    {"title": "Boiler Room: Amsterdam", "artist": "2HOT2PLAY", "url": "https://www.youtube.com/watch?v=1T_GD64wAI0", "kind": "set",
     "where": [("Hard Techno", "Hard-Bounce")]},
    {"title": "Horses", "artist": "Oscar Mulero", "url": "https://www.youtube.com/watch?v=2fP4V-KmvvI", "kind": "track",
     "where": [("Techno", "Hardgroove"), ("Hard Techno", "Hardgroove")]},
    {"title": "Underwave", "artist": "Steve Parker", "url": "https://www.youtube.com/watch?v=AQVY9PLH0jM", "kind": "track",
     "where": [("Techno", "Hardgroove"), ("Hard Techno", "Hardgroove")]},
    {"title": "Look What Your Love Has Done to Me", "artist": "Perc", "url": "https://www.youtube.com/watch?v=fhgfahfKlH8", "kind": "track",
     "where": [("Hard Techno", "Industrial Hard Techno")]},
    {"title": "Why They Hide Their Bodies Under My Garage?", "artist": "Blawan", "url": "https://www.youtube.com/watch?v=1mR6zmSTDNE", "kind": "track",
     "where": [("Hard Techno", "Industrial Hard Techno"), ("Techno", "Industrial Techno")]},
    {"title": "D-Clash", "artist": "Bryan Zentz", "url": "https://www.youtube.com/watch?v=0Cekb7z1TQs", "kind": "track",
     "where": [("Hard Techno", "Schranz")]},
    {"title": "Boiler Room Rotterdam", "artist": "DJ Rush", "url": "https://www.youtube.com/watch?v=sJl2LyNEz0s", "kind": "set",
     "where": [("Hard Techno", "Schranz")]},
    {"title": "Acid Tracks", "artist": "Phuture", "url": "https://www.youtube.com/watch?v=yKHGv6Es610", "kind": "track",
     "where": [("House", "Acid House")]},
    {"title": "Higher State of Consciousness", "artist": "Josh Wink", "url": "https://www.youtube.com/watch?v=JIsFx54hf2s", "kind": "track",
     "where": [("House", "Acid House"), ("Trance", "Acid Trance")]},
    {"title": "Feel the Volume", "artist": "Jauz", "url": "https://www.youtube.com/watch?v=mub2x7cP0Ng", "kind": "track",
     "where": [("House", "Bass House")]},
    {"title": "Rain", "artist": "Kerri Chandler", "url": "https://www.youtube.com/watch?v=weyCHkdL-HI", "kind": "track",
     "where": [("House", "Deep House")]},
    {"title": "Can You Feel It", "artist": "Mr. Fingers", "url": "https://www.youtube.com/watch?v=DrxPFBEr5Bo", "kind": "track",
     "where": [("House", "Deep House")]},
    {"title": "Around the World", "artist": "Daft Punk", "url": "https://www.youtube.com/watch?v=K0HSD_i2DvA", "kind": "track",
     "where": [("House", "French House / Filter House")]},
    {"title": "Lady (Hear Me Tonight)", "artist": "Modjo", "url": "https://www.youtube.com/watch?v=mMfxI3r_LyA", "kind": "track",
     "where": [("House", "French House / Filter House")]},
    {"title": "Where's Your Head At", "artist": "Basement Jaxx", "url": "https://www.youtube.com/watch?v=5rAOyh7YmEc", "kind": "track",
     "where": [("House", "Funky House")]},
    {"title": "Red Alert", "artist": "Basement Jaxx", "url": "https://www.youtube.com/watch?v=SJyhZ-3Z8A8", "kind": "track",
     "where": [("House", "Funky House")]},
    {"title": "After Life", "artist": "Tchami", "url": "https://www.youtube.com/watch?v=SCjMEul7Hto", "kind": "track",
     "where": [("House", "Future House"), ("Mainstage / Commercial EDM", "Future House")]},
    {"title": "Gecko", "artist": "Oliver Heldens", "url": "https://www.youtube.com/watch?v=jjx2oc2NRzA", "kind": "track",
     "where": [("House", "Future House"), ("Mainstage / Commercial EDM", "Future House")]},
    {"title": "Cola", "artist": "CamelPhat & Elderbrook", "url": "https://www.youtube.com/watch?v=qke-jOUqSXU", "kind": "track",
     "where": [("House", "Indie Tech"), ("Indie Dance", "Indie Tech")]},
    {"title": "Ready for Your Love", "artist": "Gorgon City ft. MNEK", "url": "https://www.youtube.com/watch?v=8B93tgRxMuE", "kind": "track",
     "where": [("House", "Indie Tech"), ("Indie Dance", "Indie Tech")]},
    {"title": "Bango (To the Batmobile)", "artist": "Todd Terry", "url": "https://www.youtube.com/watch?v=C8s4Jm56pwo", "kind": "track",
     "where": [("House", "Jackin House")]},
    {"title": "Weekend", "artist": "Todd Terry", "url": "https://www.youtube.com/watch?v=ivK6jTNc7gU", "kind": "track",
     "where": [("House", "Jackin House")]},
    {"title": "Somos Latinos", "artist": "Play-N-Skillz, Gente de Zona & Dale Pututi", "url": "https://www.youtube.com/watch?v=h4Xb1d3i3z8", "kind": "track",
     "where": [("House", "Latin House"), ("Latin Electronic", "Latin House")]},
    {"title": "Isla Viva", "artist": "Gente de Zona & Juan Magán", "url": "https://www.youtube.com/watch?v=2pLE6N_x2fg", "kind": "track",
     "where": [("House", "Latin House"), ("Latin Electronic", "Latin House")]},
    {"title": "Brightest Lights", "artist": "Lane 8 ft. POLIÇA", "url": "https://www.youtube.com/watch?v=CARHyGAsv6Y", "kind": "track",
     "where": [("House", "Melodic House")]},
    {"title": "Hyperfall", "artist": "Yotto", "url": "https://www.youtube.com/watch?v=n1Kqyu5qH_M", "kind": "track",
     "where": [("House", "Melodic House")]},
    {"title": "Singularity", "artist": "Stephan Bodzin", "url": "https://www.youtube.com/watch?v=AaxFuXpcQmE", "kind": "track",
     "where": [("House", "Melodic House & Techno"), ("Techno", "Melodic Techno")]},
    {"title": "Consciousness", "artist": "Anyma & Chris Avantgarde", "url": "https://www.youtube.com/watch?v=MpbZDxx44qE", "kind": "track",
     "where": [("House", "Melodic House & Techno")]},
    {"title": "Dexter", "artist": "Ricardo Villalobos", "url": "https://www.youtube.com/watch?v=04BohQTuHRI", "kind": "track",
     "where": [("House", "Minimal / Deep Tech")]},
    {"title": "Easy Lee", "artist": "Ricardo Villalobos", "url": "https://www.youtube.com/watch?v=Se4V0OHvjS8", "kind": "track",
     "where": [("House", "Minimal / Deep Tech")]},
    {"title": "Return to Oz", "artist": "Monolink", "url": "https://www.youtube.com/watch?v=bVbDz4a8oSw", "kind": "track",
     "where": [("House", "Organic House")]},
    {"title": "Ride on Time", "artist": "Black Box", "url": "https://www.youtube.com/watch?v=M0quXl_od3g", "kind": "track",
     "where": [("House", "Piano House")]},
    {"title": "Show Me Love", "artist": "Robin S", "url": "https://www.youtube.com/watch?v=Ps2Jc28tQrw", "kind": "track",
     "where": [("House", "Piano House"), ("House", "House")]},
    {"title": "Strobe", "artist": "Deadmau5", "url": "https://www.youtube.com/watch?v=tKi9Z-f6qX4", "kind": "track",
     "where": [("House", "Progressive House")]},
    {"title": "One", "artist": "Swedish House Mafia", "url": "https://www.youtube.com/watch?v=PkQ5rEJaTmk", "kind": "track",
     "where": [("House", "Progressive House")]},
    {"title": "Promised Land", "artist": "Joe Smooth", "url": "https://www.youtube.com/watch?v=BJyD_TPeJAI", "kind": "track",
     "where": [("House", "Soulful House")]},
    {"title": "Beautiful People", "artist": "Barbara Tucker", "url": "https://www.youtube.com/watch?v=N5GsLXpqfWk", "kind": "track",
     "where": [("House", "Soulful House")]},
    {"title": "Losing It", "artist": "Fisher", "url": "https://www.youtube.com/watch?v=u31thuMehjM", "kind": "track",
     "where": [("House", "Tech House")]},
    {"title": "Turn Off the Lights", "artist": "Chris Lake ft. Alexis Roberts", "url": "https://www.youtube.com/watch?v=E_wxPpRSgho", "kind": "track",
     "where": [("House", "Tech House")]},
    {"title": "If Madonna Calls", "artist": "Junior Vasquez", "url": "https://www.youtube.com/watch?v=AaaEPh6Ag9U", "kind": "track",
     "where": [("House", "Tribal House"), ("Latin Electronic", "Tribal House")]},
    {"title": "Music Is the Answer", "artist": "Danny Tenaglia & Celeda", "url": "https://www.youtube.com/watch?v=GPqD_bpA72U", "kind": "track",
     "where": [("House", "Tribal House"), ("Latin Electronic", "Tribal House")]},
    {"title": "Finally", "artist": "CeCe Peniston", "url": "https://www.youtube.com/watch?v=xk8mm1Qmt-Y", "kind": "track",
     "where": [("House", "Vocal House")]},
    {"title": "Gypsy Woman (She's Homeless)", "artist": "Crystal Waters", "url": "https://www.youtube.com/watch?v=_KztNIg4cvE", "kind": "track",
     "where": [("House", "Vocal House")]},
    {"title": "Where You Go I Go Too", "artist": "Lindstrøm", "url": "https://www.youtube.com/watch?v=BtIDbi1p2vs", "kind": "track",
     "where": [("Indie Dance", "Cosmic Dance")]},
    {"title": "Tick of the Clock", "artist": "Chromatics", "url": "https://www.youtube.com/watch?v=49FXjBiccG4", "kind": "track",
     "where": [("Indie Dance", "Dark Disco")]},
    {"title": "Nightcall", "artist": "Kavinsky", "url": "https://www.youtube.com/watch?v=MV_3Dpw-BRY", "kind": "track",
     "where": [("Indie Dance", "Dark Disco")]},
    {"title": "Pain", "artist": "Boy Harsher", "url": "https://www.youtube.com/watch?v=6Tu7ZjmdSYc", "kind": "track",
     "where": [("Indie Dance", "EBM Crossover")]},
    {"title": "Pursuit", "artist": "Gesaffelstein", "url": "https://www.youtube.com/watch?v=oRSijEW_cDM", "kind": "track",
     "where": [("Indie Dance", "EBM Crossover")]},
    {"title": "Twice", "artist": "Little Dragon", "url": "https://www.youtube.com/watch?v=TrpMncSZe-I", "kind": "track",
     "where": [("Indie Dance", "Electronic Indie")]},
    {"title": "Ready for the Floor", "artist": "Hot Chip", "url": "https://www.youtube.com/watch?v=yhASu2OjEcQ", "kind": "track",
     "where": [("Indie Dance", "Indie Dance")]},
    {"title": "What You Know", "artist": "Two Door Cinema Club", "url": "https://www.youtube.com/watch?v=YXwYJyrKK5A", "kind": "track",
     "where": [("Indie Dance", "Indie Dance")]},
    {"title": "Love Cry", "artist": "Four Tet", "url": "https://www.youtube.com/watch?v=4KgyMNoN1a8", "kind": "track",
     "where": [("Indie Dance", "Leftfield Dance")]},
    {"title": "Silhouettes", "artist": "Floating Points", "url": "https://www.youtube.com/watch?v=5ntcVE3AQsg", "kind": "track",
     "where": [("Indie Dance", "Leftfield Dance")]},
    {"title": "House of Jealous Lovers", "artist": "The Rapture", "url": "https://www.youtube.com/watch?v=xgkIDKyEP0I", "kind": "track",
     "where": [("Indie Dance", "New-Wave-Influenced Club Music")]},
    {"title": "My People", "artist": "The Presets", "url": "https://www.youtube.com/watch?v=CZe9YxJNs48", "kind": "track",
     "where": [("Indie Dance", "New-Wave-Influenced Club Music")]},
    {"title": "Fancy Footwork", "artist": "Chromeo", "url": "https://www.youtube.com/watch?v=3ZKq2ptu7qw", "kind": "track",
     "where": [("Indie Dance", "Nu-Disco Crossover")]},
    {"title": "Baby I'm Yours", "artist": "Breakbot ft. Irfane", "url": "https://www.youtube.com/watch?v=6okxuiiHx2w", "kind": "track",
     "where": [("Indie Dance", "Nu-Disco Crossover"), ("Nu Disco / Disco", "Nu Disco")]},
    {"title": "This Is My Rifle", "artist": "Combichrist", "url": "https://www.youtube.com/watch?v=7bEbCDZYXh8", "kind": "track",
     "where": [("Industrial / EBM", "Aggrotech")]},
    {"title": "Sent to Destroy", "artist": "Combichrist", "url": "https://www.youtube.com/watch?v=A8pBe1Zbd3Y", "kind": "track",
     "where": [("Industrial / EBM", "Aggrotech")]},
    {"title": "Join in the Chant", "artist": "Nitzer Ebb", "url": "https://www.youtube.com/watch?v=qejGd3sQJko", "kind": "track",
     "where": [("Industrial / EBM", "Body Music"), ("Techno", "EBM"), ("Industrial / EBM", "EBM"), ("Industrial / EBM", "Electro-Industrial")]},
    {"title": "Hellraiser", "artist": "Suicide Commando", "url": "https://www.youtube.com/watch?v=hj8hSymqL5g", "kind": "track",
     "where": [("Industrial / EBM", "Dark Electro")]},
    {"title": "Der Mussolini", "artist": "DAF", "url": "https://www.youtube.com/watch?v=6etM3FWwEZo", "kind": "track",
     "where": [("Techno", "EBM"), ("Industrial / EBM", "EBM")]},
    {"title": "Mindphaser", "artist": "Front Line Assembly", "url": "https://www.youtube.com/watch?v=GPxrznzU43U", "kind": "track",
     "where": [("Industrial / EBM", "Electro-Industrial")]},
    {"title": "Jesus Built My Hotrod", "artist": "Ministry", "url": "https://www.youtube.com/watch?v=GXCh9OhDiCI", "kind": "track",
     "where": [("Industrial / EBM", "Industrial")]},
    {"title": "Megalomaniac", "artist": "KMFDM", "url": "https://www.youtube.com/watch?v=j9-jJvTHnhI", "kind": "track",
     "where": [("Industrial / EBM", "Industrial")]},
    {"title": "Hamburger Lady", "artist": "Throbbing Gristle", "url": "https://www.youtube.com/watch?v=WiWGzn39v54", "kind": "track",
     "where": [("Industrial / EBM", "Industrial / Noise")]},
    {"title": "Birthdeath Experience", "artist": "Whitehouse", "url": "https://www.youtube.com/watch?v=L2_1irrvE0Q", "kind": "track",
     "where": [("Industrial / EBM", "Industrial / Noise")]},
    {"title": "Flesh", "artist": "A Split-Second", "url": "https://www.youtube.com/watch?v=VsG2_465Srs", "kind": "track",
     "where": [("Industrial / EBM", "New Beat")]},
    {"title": "The Sound of C", "artist": "Confetti's", "url": "https://www.youtube.com/watch?v=s0_B0rO7jsg", "kind": "track",
     "where": [("Industrial / EBM", "New Beat")]},
    {"title": "Imminent Starvation (Tentack One)", "artist": "VJ Bolverk", "url": "https://www.youtube.com/watch?v=1BnXkL3mw5Y", "kind": "track",
     "where": [("Industrial / EBM", "Power Noise")]},
    {"title": "The Experiment", "artist": "Converter", "url": "https://www.youtube.com/watch?v=S2iq9iqHEeI", "kind": "track",
     "where": [("Industrial / EBM", "Rhythmic Noise")]},
    {"title": "Blue Monday", "artist": "New Order", "url": "https://www.youtube.com/watch?v=iOEJHNZpeck", "kind": "track",
     "where": [("Industrial / EBM", "Electronic Post-Punk")]},
    {"title": "Nag Nag Nag", "artist": "Cabaret Voltaire", "url": "https://www.youtube.com/watch?v=pWGZWYrR5Nw", "kind": "track",
     "where": [("Industrial / EBM", "Electronic Post-Punk")]},
    {"title": "Rumbera", "artist": "Systema Solar", "url": "https://www.youtube.com/watch?v=UzCENuyKX4E", "kind": "track",
     "where": [("Latin Electronic", "Electronic Cumbia / Cumbia Digital")]},
    {"title": "Rio Arriba", "artist": "Chancha Via Circuito", "url": "https://www.youtube.com/watch?v=Kgs4odAl9V4", "kind": "track",
     "where": [("Latin Electronic", "Electronic Cumbia / Cumbia Digital")]},
    {"title": "Polaris", "artist": "Nortec Collective", "url": "https://www.youtube.com/watch?v=mGUUTmnVEIE", "kind": "track",
     "where": [("Latin Electronic", "Latin Bass")]},
    {"title": "Mexico", "artist": "Mexican Institute of Sound", "url": "https://www.youtube.com/watch?v=5fIkNzorfOs", "kind": "track",
     "where": [("Latin Electronic", "Latin Bass")]},
    {"title": "Lean On", "artist": "Major Lazer & DJ Snake ft. MØ", "url": "https://www.youtube.com/watch?v=YqeW9_5kURI", "kind": "track",
     "where": [("Latin Electronic", "Latin Club")]},
    {"title": "Colibria", "artist": "Nicola Cruz & Huaira", "url": "https://www.youtube.com/watch?v=iRV90c_uWpQ", "kind": "track",
     "where": [("Latin Electronic", "Latin Electronic")]},
    {"title": "Que Que", "artist": "Dillon Francis & Diplo ft. Maluca", "url": "https://www.youtube.com/watch?v=etT8U-7sXH4", "kind": "track",
     "where": [("Latin Electronic", "Moombahton")]},
    {"title": "Pon de Floor", "artist": "Major Lazer ft. Vybz Kartel", "url": "https://www.youtube.com/watch?v=pHEkIiQpwI8", "kind": "track",
     "where": [("Latin Electronic", "Moombahton")]},
    {"title": "Pai", "artist": "Bad Gyal", "url": "https://www.youtube.com/watch?v=aR5P4rzZJm4", "kind": "track",
     "where": [("Latin Electronic", "Neo-Perreo")]},
    {"title": "Zorra", "artist": "Bad Gyal", "url": "https://www.youtube.com/watch?v=ND2riyDD_oo", "kind": "track",
     "where": [("Latin Electronic", "Neo-Perreo")]},
    {"title": "Boiler Room: Caracas", "artist": "DJ Babatr", "url": "https://www.youtube.com/watch?v=dwxPSYQlqWQ", "kind": "set",
     "where": [("Latin Electronic", "Raptor House / Changa Tuki")]},
    {"title": "Raptor House Mix 2024", "artist": "DJ Darrel", "url": "https://www.youtube.com/watch?v=9-h6yJeR3rE", "kind": "set",
     "where": [("Latin Electronic", "Raptor House / Changa Tuki")]},
    {"title": "Toco El Cielo", "artist": "Manco The Sound", "url": "https://www.youtube.com/watch?v=cOpQoFwHSd4", "kind": "track",
     "where": [("Latin Electronic", "Tribal / Guaracha")]},
    {"title": "Inténtalo", "artist": "3BallMTY ft. El Bebeto & América Sierra", "url": "https://www.youtube.com/watch?v=LRYNWfJzfVE", "kind": "track",
     "where": [("Latin Electronic", "Tribal Guarachero")]},
    {"title": "Safaera", "artist": "Bad Bunny, Jowell & Randy, Ñengo Flow", "url": "https://www.youtube.com/watch?v=jCQ_6XbATPc", "kind": "track",
     "where": [("Latin Electronic", "Electronic Reggaeton Crossover")]},
    {"title": "Gasolina", "artist": "Daddy Yankee", "url": "https://www.youtube.com/watch?v=CCF1_jI8Prk", "kind": "track",
     "where": [("Latin Electronic", "Electronic Reggaeton Crossover")]},
    {"title": "Bigfoot", "artist": "W&W", "url": "https://www.youtube.com/watch?v=9ytt1ELA82U", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Big Room")]},
    {"title": "Ghosts 'n' Stuff", "artist": "Deadmau5 ft. Rob Swire", "url": "https://www.youtube.com/watch?v=h7ArUgxtlJs", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Electro House")]},
    {"title": "Take Over Control", "artist": "Afrojack ft. Eva Simons", "url": "https://www.youtube.com/watch?v=adGVpCsf9N4", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Electro House")]},
    {"title": "Levels", "artist": "Avicii", "url": "https://www.youtube.com/watch?v=_ovdm2yX4MA", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Festival Progressive House")]},
    {"title": "Heroes (We Could Be)", "artist": "Alesso ft. Tove Lo", "url": "https://www.youtube.com/watch?v=a7SouU3ECpU", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Festival Progressive House"), ("Mainstage / Commercial EDM", "Mainstage")]},
    {"title": "Kill Me Slow", "artist": "David Guetta & MORTEN", "url": "https://www.youtube.com/watch?v=CJ2g5BsnmMw", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Future Rave")]},
    {"title": "Detroit 3 AM", "artist": "David Guetta & MORTEN", "url": "https://www.youtube.com/watch?v=1W6QyZQY1is", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Future Rave")]},
    {"title": "Red Lights", "artist": "Tiësto", "url": "https://www.youtube.com/watch?v=CFF0mV24WCY", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Mainstage")]},
    {"title": "Speed House Collective · DJ set in NYC", "artist": "yunji", "url": "https://www.youtube.com/watch?v=g7JflJbEehg", "kind": "set",
     "where": [("Mainstage / Commercial EDM", "Speed House")]},
    {"title": "carRADIO 050 · Bass House, UKG and Speed House", "artist": "Henry Fong", "url": "https://www.youtube.com/watch?v=hqXJWXaRAYY", "kind": "set",
     "where": [("Mainstage / Commercial EDM", "Speed House")]},
    {"title": "This Is What You Came For", "artist": "Calvin Harris ft. Rihanna", "url": "https://www.youtube.com/watch?v=kOkQ4T5WO9E", "kind": "track",
     "where": [("Mainstage / Commercial EDM", "Commercial EDM")]},
    {"title": "Supernature", "artist": "Cerrone", "url": "https://www.youtube.com/watch?v=cJ5V3OZdIZM", "kind": "track",
     "where": [("Nu Disco / Disco", "Cosmic Disco")]},
    {"title": "From Here to Eternity", "artist": "Giorgio Moroder", "url": "https://www.youtube.com/watch?v=qTFEyFEu1Fk", "kind": "track",
     "where": [("Nu Disco / Disco", "Cosmic Disco"), ("Nu Disco / Disco", "Space Disco")]},
    {"title": "Le Freak", "artist": "Chic", "url": "https://www.youtube.com/watch?v=7PC-AcrHEKU", "kind": "track",
     "where": [("Nu Disco / Disco", "Disco")]},
    {"title": "September", "artist": "Earth, Wind & Fire", "url": "https://www.youtube.com/watch?v=Gs069dndIYk", "kind": "track",
     "where": [("Nu Disco / Disco", "Disco")]},
    {"title": "Hypnotized", "artist": "Purple Disco Machine & Sophie and the Giants", "url": "https://www.youtube.com/watch?v=VbQqV8_Ykow", "kind": "track",
     "where": [("Nu Disco / Disco", "Disco House"), ("Nu Disco / Disco", "Nu Disco")]},
    {"title": "Free Yourself", "artist": "Jessie Ware", "url": "https://www.youtube.com/watch?v=aD7F6M9fsms", "kind": "track",
     "where": [("Nu Disco / Disco", "Disco House")]},
    {"title": "One More Time", "artist": "Daft Punk", "url": "https://www.youtube.com/watch?v=FGBhQbmPwH8", "kind": "track",
     "where": [("Nu Disco / Disco", "French Touch")]},
    {"title": "Toop Toop", "artist": "Cassius", "url": "https://www.youtube.com/watch?v=wBZM6RSqW-Y", "kind": "track",
     "where": [("Nu Disco / Disco", "French Touch")]},
    {"title": "You Think You're a Man", "artist": "Divine", "url": "https://www.youtube.com/watch?v=69ADxaSqRNY", "kind": "track",
     "where": [("Nu Disco / Disco", "Hi-NRG")]},
    {"title": "You Make Me Feel (Mighty Real)", "artist": "Sylvester", "url": "https://www.youtube.com/watch?v=gD6cPE2BHic", "kind": "track",
     "where": [("Nu Disco / Disco", "Hi-NRG")]},
    {"title": "I Like Chopin", "artist": "Gazebo", "url": "https://www.youtube.com/watch?v=Dtrgwqei7ww", "kind": "track",
     "where": [("Nu Disco / Disco", "Italo Disco")]},
    {"title": "Vamos a la playa", "artist": "Righeira", "url": "https://www.youtube.com/watch?v=x0OMFm8FO90", "kind": "track",
     "where": [("Nu Disco / Disco", "Italo Disco")]},
    {"title": "Magic Fly", "artist": "Space", "url": "https://www.youtube.com/watch?v=TONnzySDbqk", "kind": "track",
     "where": [("Nu Disco / Disco", "Space Disco")]},
    {"title": "Busy Earnin'", "artist": "Jungle", "url": "https://www.youtube.com/watch?v=BcsfftwLUf0", "kind": "track",
     "where": [("Nu Disco / Disco", "Electronic Funk / Soul Crossover")]},
    {"title": "Overnight", "artist": "Parcels", "url": "https://www.youtube.com/watch?v=BTdBc2Ba8ts", "kind": "track",
     "where": [("Nu Disco / Disco", "Electronic Funk / Soul Crossover")]},
    {"title": "Shaari Avadon", "artist": "Xenomorph", "url": "https://www.youtube.com/watch?v=cdvD9oiJ1C4", "kind": "track",
     "where": [("Psy-Trance", "Darkpsy")]},
    {"title": "Nritya Shastra", "artist": "Kindzadza vs. Furious vs. Psykovsky vs. Cosmo", "url": "https://www.youtube.com/watch?v=Whjsr5PPlyo", "kind": "track",
     "where": [("Psy-Trance", "Darkpsy")]},
    {"title": "Live at Psy-Fi 2017", "artist": "Kindzadza", "url": "https://www.youtube.com/watch?v=Ivh_CHbstvE", "kind": "set",
     "where": [("Psy-Trance", "Forest Psy")]},
    {"title": "Nocturnal (full album)", "artist": "Egorythmia", "url": "https://www.youtube.com/watch?v=KL2x8QeHZgw", "kind": "set",
     "where": [("Psy-Trance", "Forest Psy")]},
    {"title": "Eye to Eye", "artist": "Astrix", "url": "https://www.youtube.com/watch?v=n7cewNC40aE", "kind": "track",
     "where": [("Psy-Trance", "Full-On")]},
    {"title": "Vicious Delicious", "artist": "Infected Mushroom", "url": "https://www.youtube.com/watch?v=bDcLmkl38tw", "kind": "track",
     "where": [("Psy-Trance", "Full-On")]},
    {"title": "God Is God", "artist": "Juno Reactor", "url": "https://www.youtube.com/watch?v=KU-AzCXbLG8", "kind": "track",
     "where": [("Psy-Trance", "Goa Trance")]},
    {"title": "Mahadeva", "artist": "Astral Projection", "url": "https://www.youtube.com/watch?v=Ix0lduF1Co4", "kind": "track",
     "where": [("Psy-Trance", "Goa Trance")]},
    {"title": "Context High", "artist": "Ajja", "url": "https://www.youtube.com/watch?v=Z7YdfzCPZhM", "kind": "track",
     "where": [("Psy-Trance", "Hi-Tech Psy")]},
    {"title": "Live at Psy-Fi 2017", "artist": "Ajja", "url": "https://www.youtube.com/watch?v=JEPbmXSXmns", "kind": "set",
     "where": [("Psy-Trance", "Hi-Tech Psy")]},
    {"title": "Spiritual Beings", "artist": "Ace Ventura & Asgard", "url": "https://www.youtube.com/watch?v=xpX8LjhxkGw", "kind": "track",
     "where": [("Psy-Trance", "Progressive Psy")]},
    {"title": "Ozora Festival 2025", "artist": "Ritmo", "url": "https://www.youtube.com/watch?v=S2sVkY78KkQ", "kind": "set",
     "where": [("Psy-Trance", "Progressive Psy")]},
    {"title": "Synthetic Memories", "artist": "Djantrix & Spirit Architect", "url": "https://www.youtube.com/watch?v=RYdG5c5A0ds", "kind": "track",
     "where": [("Psy-Trance", "Psy-Tech")]},
    {"title": "Unite · Psytrance Sessions", "artist": "Zyce", "url": "https://www.youtube.com/watch?v=8OdaW7tCYds", "kind": "set",
     "where": [("Psy-Trance", "Psy-Tech")]},
    {"title": "Divine Moments of Truth", "artist": "Shpongle", "url": "https://www.youtube.com/watch?v=igy8q2nWg-o", "kind": "track",
     "where": [("Psy-Trance", "Psychedelic")]},
    {"title": "Nothing Lasts", "artist": "Shpongle", "url": "https://www.youtube.com/watch?v=_VuVA0P10u8", "kind": "track",
     "where": [("Psy-Trance", "Psychedelic")]},
    {"title": "Chronicles of the Past", "artist": "Yamaraja & Crone", "url": "https://www.youtube.com/watch?v=nkFKOVo4qtU", "kind": "track",
     "where": [("Psy-Trance", "Psycore")]},
    {"title": "Psychotic Disorders", "artist": "Yamaraja", "url": "https://www.youtube.com/watch?v=RZkz1HpFsMA", "kind": "track",
     "where": [("Psy-Trance", "Psycore")]},
    {"title": "Becoming Insane", "artist": "Infected Mushroom", "url": "https://www.youtube.com/watch?v=wVwQYSVNJVM", "kind": "track",
     "where": [("Psy-Trance", "Psytrance")]},
    {"title": "Acperience 1", "artist": "Hardfloor", "url": "https://www.youtube.com/watch?v=Un4CeV_l3pI", "kind": "track",
     "where": [("Techno", "Acid Techno")]},
    {"title": "Acid Phase", "artist": "Emmanuel Top", "url": "https://www.youtube.com/watch?v=SfqVKScM490", "kind": "track",
     "where": [("Techno", "Acid Techno")]},
    {"title": "Amber Decay", "artist": "Kangding Ray", "url": "https://www.youtube.com/watch?v=LO40CaFEG5Y", "kind": "track",
     "where": [("Techno", "Broken Techno")]},
    {"title": "Broken", "artist": "Perc & Truss", "url": "https://www.youtube.com/watch?v=21075TJ23i8", "kind": "track",
     "where": [("Techno", "Broken Techno")]},
    {"title": "Sgadi Li Mi", "artist": "Charlotte de Witte", "url": "https://www.youtube.com/watch?v=M6KMTUSWsW0", "kind": "track",
     "where": [("Techno", "Dark Techno")]},
    {"title": "Hypnotized", "artist": "Amelie Lens", "url": "https://www.youtube.com/watch?v=Mt4YyoqhHuA", "kind": "track",
     "where": [("Techno", "Dark Techno"), ("Techno", "Peak-Time / Driving")]},
    {"title": "Phylyps Trak", "artist": "Basic Channel", "url": "https://www.youtube.com/watch?v=6a4HlgmlMuw", "kind": "track",
     "where": [("Techno", "Deep Techno"), ("Techno", "Dub Techno")]},
    {"title": "Waterfall", "artist": "Rrose", "url": "https://www.youtube.com/watch?v=kjv1kSpyW9s", "kind": "track",
     "where": [("Techno", "Deep Techno"), ("Techno", "Hypnotic Techno")]},
    {"title": "No UFO's", "artist": "Model 500", "url": "https://www.youtube.com/watch?v=xcdOBLH_AXs", "kind": "track",
     "where": [("Techno", "Detroit Techno")]},
    {"title": "Subzero", "artist": "Ben Klock", "url": "https://www.youtube.com/watch?v=wbdb1rWV9Jw", "kind": "track",
     "where": [("Techno", "Hypnotic Techno")]},
    {"title": "Eternity", "artist": "Anyma", "url": "https://www.youtube.com/watch?v=xAfNUoqQppU", "kind": "track",
     "where": [("Techno", "Melodic Techno")]},
    {"title": "Spastik", "artist": "Plastikman", "url": "https://www.youtube.com/watch?v=Nsct-e-HVE0", "kind": "track",
     "where": [("Techno", "Minimal Techno")]},
    {"title": "Minus", "artist": "Robert Hood", "url": "https://www.youtube.com/watch?v=dJfAPSZEK5s", "kind": "track",
     "where": [("Techno", "Minimal Techno")]},
    {"title": "Welcome Back Devil XXL, Paris", "artist": "SHLØMO", "url": "https://www.youtube.com/watch?v=BuKd71P2XRs", "kind": "set",
     "where": [("Techno", "Psy-Techno")]},
    {"title": "HÖR Berlin", "artist": "SHLØMO", "url": "https://www.youtube.com/watch?v=8WzFoUPyvgY", "kind": "set",
     "where": [("Techno", "Psy-Techno")]},
    {"title": "Apollo", "artist": "Charlotte de Witte", "url": "https://www.youtube.com/watch?v=uxNjgtFTkLE", "kind": "track",
     "where": [("Techno", "Raw Techno")]},
    {"title": "The Bells", "artist": "Jeff Mills", "url": "https://www.youtube.com/watch?v=S-BlgAQ7uRQ", "kind": "track",
     "where": [("Techno", "Techno")]},
    {"title": "DJ set from The Warehouse Project · DJ Mag", "artist": "Joseph Capriati", "url": "https://www.youtube.com/watch?v=2jzBoRgTojw", "kind": "set",
     "where": [("Techno", "Tribal Techno")]},
    {"title": "Awakenings x Metamorfosi ADE 2024", "artist": "Joseph Capriati", "url": "https://www.youtube.com/watch?v=KV38B1wNHxo", "kind": "set",
     "where": [("Techno", "Tribal Techno")]},
    {"title": "Superstring", "artist": "Cygnus X", "url": "https://www.youtube.com/watch?v=qevKV5rEOJk", "kind": "track",
     "where": [("Trance", "Acid Trance")]},
    {"title": "Intercity", "artist": "Solarstone", "url": "https://www.youtube.com/watch?v=TpAunLa2Lhk", "kind": "track",
     "where": [("Trance", "Deep Trance")]},
    {"title": "1998", "artist": "Binary Finary", "url": "https://www.youtube.com/watch?v=6JojPCCJF0E", "kind": "track",
     "where": [("Trance", "Hypnotic Trance")]},
    {"title": "We Control the Sunlight", "artist": "Aly & Fila ft. Jwaydan", "url": "https://www.youtube.com/watch?v=Ad_eViMKuF8", "kind": "track",
     "where": [("Trance", "Main-Floor Trance")]},
    {"title": "Communication", "artist": "Armin van Buuren", "url": "https://www.youtube.com/watch?v=bn1ycNxQMvk", "kind": "track",
     "where": [("Trance", "Main-Floor Trance")]},
    {"title": "Arcadia", "artist": "Gabriel & Dresden", "url": "https://www.youtube.com/watch?v=BmAwELOCKaA", "kind": "track",
     "where": [("Trance", "Progressive Trance")]},
    {"title": "Xpander", "artist": "Sasha", "url": "https://www.youtube.com/watch?v=xyBi-omSdGY", "kind": "track",
     "where": [("Trance", "Progressive Trance")]},
    {"title": "Future Trance Classics · A State of Trance Rotterdam 2024", "artist": "ReOrder", "url": "https://www.youtube.com/watch?v=HCFvEP-y5-o", "kind": "set",
     "where": [("Trance", "Raw Trance")]},
    {"title": "Live at A State of Trance 1000", "artist": "Will Atkinson", "url": "https://www.youtube.com/watch?v=j_LKJgVrywQ", "kind": "set",
     "where": [("Trance", "Raw Trance")]},
    {"title": "Proximus", "artist": "Mauro Picotto", "url": "https://www.youtube.com/watch?v=uPGpsKmK7g0", "kind": "track",
     "where": [("Trance", "Tech Trance")]},
    {"title": "For an Angel", "artist": "Paul van Dyk", "url": "https://www.youtube.com/watch?v=sRvEwXDxz_I", "kind": "track",
     "where": [("Trance", "Trance")]},
    {"title": "Airwave", "artist": "Rank 1", "url": "https://www.youtube.com/watch?v=ypDtUUtuNzQ", "kind": "track",
     "where": [("Trance", "Uplifting Trance")]},
    {"title": "Sun & Moon", "artist": "Above & Beyond ft. Richard Bedford", "url": "https://www.youtube.com/watch?v=ll5ykbAumD4", "kind": "track",
     "where": [("Trance", "Uplifting Trance"), ("Trance", "Vocal Trance")]},
    {"title": "Silence", "artist": "Delerium", "url": "https://www.youtube.com/watch?v=a4kvVNWnFwk", "kind": "track",
     "where": [("Trance", "Vocal Trance")]},
    {"title": "Mosh Pit", "artist": "Flosstradamus ft. Casino", "url": "https://www.youtube.com/watch?v=KNByf1o4T_8", "kind": "track",
     "where": [("Trap / Future Bass", "EDM Trap")]},
    {"title": "Prison Riot", "artist": "Flosstradamus, GTA & Lil Jon", "url": "https://www.youtube.com/watch?v=OcvunrplrZc", "kind": "track",
     "where": [("Trap / Future Bass", "Festival Trap")]},
    {"title": "Light", "artist": "San Holo", "url": "https://www.youtube.com/watch?v=uOFTqVi-qp4", "kind": "track",
     "where": [("Trap / Future Bass", "Future Bass")]},
    {"title": "Better Not", "artist": "Louis The Child ft. Wafia", "url": "https://www.youtube.com/watch?v=u5kP_nfFVt4", "kind": "track",
     "where": [("Trap / Future Bass", "Future Bass")]},
    {"title": "Mixmag Lab NYC", "artist": "Kayzo", "url": "https://www.youtube.com/watch?v=ujzdQ-Zvlt8", "kind": "set",
     "where": [("Trap / Future Bass", "Hardwave")]},
    {"title": "Live at Escape 2025", "artist": "Kayzo", "url": "https://www.youtube.com/watch?v=vg56hdP_nx8", "kind": "set",
     "where": [("Trap / Future Bass", "Hardwave")]},
    {"title": "Híbrido", "artist": "TroyBoi", "url": "https://www.youtube.com/watch?v=G8K6S0hAFwk", "kind": "track",
     "where": [("Trap / Future Bass", "Hybrid Trap")]},
    {"title": "Wonky", "artist": "TroyBoi", "url": "https://www.youtube.com/watch?v=ihwKdQuVQRo", "kind": "track",
     "where": [("Trap / Future Bass", "Hybrid Trap")]},
    {"title": "Good Things Fall Apart", "artist": "ILLENIUM & Jon Bellion", "url": "https://www.youtube.com/watch?v=XpmeVNxZ-Ks", "kind": "track",
     "where": [("Trap / Future Bass", "Melodic Bass")]},
    {"title": "Blame", "artist": "Ekali & ZHU", "url": "https://www.youtube.com/watch?v=L7S7ZvpCcKI", "kind": "track",
     "where": [("Trap / Future Bass", "Wave")]},
    {"title": "Waves", "artist": "Tentendo ft. Blasko, Jordan Dennis & Rahel", "url": "https://www.youtube.com/watch?v=-gWAc5qt4LE", "kind": "track",
     "where": [("Trap / Future Bass", "Wave")]},
    {"title": "Fill Me In", "artist": "Craig David", "url": "https://www.youtube.com/watch?v=3imO7PFU5cI", "kind": "track",
     "where": [("UK Garage / Bassline", "2-Step")]},
    {"title": "Sweet Like Chocolate", "artist": "Shanks & Bigfoot", "url": "https://www.youtube.com/watch?v=OQCQnARnKbc", "kind": "track",
     "where": [("UK Garage / Bassline", "2-Step")]},
    {"title": "Battle", "artist": "Wookie", "url": "https://www.youtube.com/watch?v=-15oU-lNSnc", "kind": "track",
     "where": [("UK Garage / Bassline", "4x4 Garage")]},
    {"title": "Heartbroken", "artist": "T2", "url": "https://www.youtube.com/watch?v=F4uy0_ZltXU", "kind": "track",
     "where": [("UK Garage / Bassline", "Bassline")]},
    {"title": "Neighbourhood", "artist": "Zed Bias", "url": "https://www.youtube.com/watch?v=w6-MlRH1VFE", "kind": "track",
     "where": [("UK Garage / Bassline", "Dark Garage")]},
    {"title": "Buck & Bury", "artist": "El-B", "url": "https://www.youtube.com/watch?v=fwAKC1ML-Ak", "kind": "track",
     "where": [("UK Garage / Bassline", "Dark Garage")]},
    {"title": "Etched Headplate", "artist": "Burial", "url": "https://www.youtube.com/watch?v=quMLGB_K7K8", "kind": "track",
     "where": [("UK Garage / Bassline", "Future Garage")]},
    {"title": "RIP Groove", "artist": "Double 99", "url": "https://www.youtube.com/watch?v=uR3Vw8J8vUo", "kind": "track",
     "where": [("UK Garage / Bassline", "Speed Garage")]},
    {"title": "You Don't Know Me", "artist": "Armand Van Helden ft. Duane Harden", "url": "https://www.youtube.com/watch?v=-bsONE-kZwI", "kind": "track",
     "where": [("UK Garage / Bassline", "Speed Garage")]},
    {"title": "Bound 4 da Reload", "artist": "Oxide & Neutrino", "url": "https://www.youtube.com/watch?v=q5T1EIiDSmo", "kind": "track",
     "where": [("UK Garage / Bassline", "UK Garage")]},
]
