# Generated by Django 5.2.17 on 2026-10-04 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupnotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupnotice',
            name='notice_valid_kind',
        ),
        migrations.AlterField(
            model_name='groupnotice',
            name='kind',
            field=models.CharField(choices=[('joined', 'Joined the group'), ('left', 'Left the group'), ('promoted', 'Promoted to owner')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='groupnotice',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['joined', 'left', 'promoted'])), name='notice_valid_kind'),
        ),
    ]
