# Generated by Django 5.2.17 on 2026-10-04 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupnotice_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created a group'), ('joined', 'Joined a group'), ('left', 'Left a group'), ('removed', 'Removed from a group')], max_length=8)),
                ('group_name', models.CharField(max_length=120)),
                ('event_title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='groups.attendancegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='grouphistory_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['created', 'joined', 'left', 'removed'])), name='grouphistory_valid_kind')],
            },
        ),
    ]
