# Copyright © 2026 Xander Chen. All rights reserved.
# Generated by Django 5.2.17 on 2026-09-27 21:19

import discovery.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreListeningReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist_credit', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('kind', models.CharField(choices=[('track', 'Track'), ('set', 'Set'), ('artist_page', 'Artist page')], max_length=11)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('ticket_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_hidden', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bpm_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bpm_max__isnull', True), ('bpm_min__isnull', True)), models.Q(('bpm_max__gte', models.F('bpm_min')), ('bpm_max__isnull', False), ('bpm_min__gt', 0), ('bpm_min__isnull', False)), _connector='OR'), name='discovery_genrecategory_bpm_range'), models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_case_unique')],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.event')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.genrecategory')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', through='discovery.EventCategory', to='discovery.genrecategory'),
        ),
        migrations.CreateModel(
            name='GenreReferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.genrecategory')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.genrelisteningreference')),
            ],
        ),
        migrations.AddField(
            model_name='genrelisteningreference',
            name='categories',
            field=models.ManyToManyField(related_name='listening_references', through='discovery.GenreReferenceCategory', to='discovery.genrecategory'),
        ),
        migrations.CreateModel(
            name='GenreTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bpm_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='discovery.genrecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenreReferenceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.genrelisteningreference')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.genretag')),
            ],
        ),
        migrations.AddField(
            model_name='genrelisteningreference',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='listening_references', through='discovery.GenreReferenceTag', to='discovery.genretag'),
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.event')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discovery.genretag')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', through='discovery.EventTag', to='discovery.genretag'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timezone', models.CharField(max_length=64, validators=[discovery.validators.validate_timezone])),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_venues', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='discovery.venue'),
        ),
        migrations.CreateModel(
            name='EventChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('event_edit', 'Event edit'), ('venue_details_edit', 'Venue details edit')], max_length=18)),
                ('changes', models.JSONField(validators=[discovery.validators.validate_changes])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_changes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='discovery.event')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['event_edit', 'venue_details_edit'])), name='event_change_valid_kind')],
            },
        ),
        migrations.CreateModel(
            name='EventFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follows', to='discovery.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='event_follow_unique')],
            },
        ),
        migrations.CreateModel(
            name='EventListeningReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist_credit', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('kind', models.CharField(choices=[('track', 'Track'), ('set', 'Set'), ('artist_page', 'Artist page')], max_length=11)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_references', to='discovery.event')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['track', 'set', 'artist_page'])), name='eventlisteningreference_valid_kind')],
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('incorrect_information', 'Incorrect information'), ('spam_scam', 'Spam or scam'), ('safety_concern', 'Safety concern'), ('other', 'Other')], max_length=24)),
                ('explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], db_index=True, default='pending', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='discovery.event')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'dismissed', 'actioned'])), name='report_valid_status'), models.CheckConstraint(condition=models.Q(('reason__in', ['incorrect_information', 'spam_scam', 'safety_concern', 'other'])), name='report_valid_reason')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(fields=('event', 'category'), name='event_category_unique'),
        ),
        migrations.AddConstraint(
            model_name='genrereferencecategory',
            constraint=models.UniqueConstraint(fields=('reference', 'category'), name='genre_reference_category_unique'),
        ),
        migrations.AddConstraint(
            model_name='genretag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bpm_max__isnull', True), ('bpm_min__isnull', True)), models.Q(('bpm_max__gte', models.F('bpm_min')), ('bpm_max__isnull', False), ('bpm_min__gt', 0), ('bpm_min__isnull', False)), _connector='OR'), name='discovery_genretag_bpm_range'),
        ),
        migrations.AddConstraint(
            model_name='genretag',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='tag_category_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='genretag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='tag_name_case_unique'),
        ),
        migrations.AddConstraint(
            model_name='genrereferencetag',
            constraint=models.UniqueConstraint(fields=('reference', 'tag'), name='genre_reference_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='genrelisteningreference',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['track', 'set', 'artist_page'])), name='genrelisteningreference_valid_kind'),
        ),
        migrations.AddConstraint(
            model_name='eventtag',
            constraint=models.UniqueConstraint(fields=('event', 'tag'), name='event_tag_unique'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='venue_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='venue_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='venue_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_end_after_start'),
        ),
    ]
