# Generated by Django 5.2.17 on 2026-09-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genrecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'genre categories'},
        ),
    ]
