# Generated by Django 5.2.17 on 2026-09-30 12:21

from django.db import migrations, models


def cap_legacy_bpm(apps, schema_editor):
    # Keep older curated classifications displayable without inventing a value above 200.
    for name in ("GenreCategory", "GenreTag"):
        model = apps.get_model("discovery", name)
        model.objects.using(schema_editor.connection.alias).filter(bpm_max__gt=200).update(
            bpm_max=200, bpm_max_open=True,
        )
        model.objects.using(schema_editor.connection.alias).filter(bpm_min__gt=200).update(bpm_min=200)


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_alter_genrecategory_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genrecategory',
            name='discovery_genrecategory_bpm_range',
        ),
        migrations.RemoveConstraint(
            model_name='genretag',
            name='discovery_genretag_bpm_range',
        ),
        migrations.AddField(
            model_name='genrecategory',
            name='bpm_max_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genretag',
            name='bpm_max_open',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(cap_legacy_bpm, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='genrecategory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bpm_max__isnull', True), ('bpm_max_open', False), ('bpm_min__isnull', True)), models.Q(('bpm_max__gte', models.F('bpm_min')), ('bpm_max__isnull', False), ('bpm_max__lte', 200), ('bpm_min__gt', 0), ('bpm_min__isnull', False), ('bpm_min__lte', 200), models.Q(('bpm_max_open', False), ('bpm_max', 200), _connector='OR')), _connector='OR'), name='discovery_genrecategory_bpm_range'),
        ),
        migrations.AddConstraint(
            model_name='genretag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bpm_max__isnull', True), ('bpm_max_open', False), ('bpm_min__isnull', True)), models.Q(('bpm_max__gte', models.F('bpm_min')), ('bpm_max__isnull', False), ('bpm_max__lte', 200), ('bpm_min__gt', 0), ('bpm_min__isnull', False), ('bpm_min__lte', 200), models.Q(('bpm_max_open', False), ('bpm_max', 200), _connector='OR')), _connector='OR'), name='discovery_genretag_bpm_range'),
        ),
    ]
