# Generated by Django 5.2.17 on 2026-09-30 13:44

from django.db import migrations, models


RESTORED_TAG_MAXIMA = {
    ("Hard Dance / Hardcore", "Frenchcore", 190): 220,
    ("Hard Dance / Hardcore", "Uptempo", 185): 220,
    ("Hard Dance / Hardcore", "Terror / Terrorcore", 200): 300,
    ("Hard Dance / Hardcore", "Breakcore", 160): 220,
    ("Psy-Trance", "Psycore", 180): 300,
    ("Psy-Trance", "Hi-Tech Psy", 170): 220,
}


def restore_capped_ranges(apps, schema_editor):
    """Restore only the six imported CSV ranges; preserve other curated edits."""
    Category = apps.get_model("discovery", "GenreCategory")
    Tag = apps.get_model("discovery", "GenreTag")
    database = schema_editor.connection.alias
    Category.objects.using(database).filter(
        name="Hard Dance / Hardcore", bpm_min=150, bpm_max=200, bpm_max_open=True,
    ).update(bpm_max_open=False)
    for (category, name, minimum), maximum in RESTORED_TAG_MAXIMA.items():
        Tag.objects.using(database).filter(
            category__name=category, name=name, bpm_min=minimum,
            bpm_max=200, bpm_max_open=True,
        ).update(bpm_max=maximum, bpm_max_open=False)


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_remove_genrecategory_discovery_genrecategory_bpm_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genrecategory',
            name='discovery_genrecategory_bpm_range',
        ),
        migrations.RemoveConstraint(
            model_name='genretag',
            name='discovery_genretag_bpm_range',
        ),
        migrations.AlterField(
            model_name='genrecategory',
            name='bpm_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genrecategory',
            name='bpm_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='bpm_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genretag',
            name='bpm_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(restore_capped_ranges),
        migrations.RemoveField(
            model_name='genrecategory',
            name='bpm_max_open',
        ),
        migrations.RemoveField(
            model_name='genretag',
            name='bpm_max_open',
        ),
        migrations.AddConstraint(
            model_name='genrecategory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bpm_max__isnull', True), ('bpm_min__isnull', True)), models.Q(('bpm_max__gte', models.F('bpm_min')), ('bpm_max__isnull', False), ('bpm_min__gt', 0), ('bpm_min__isnull', False)), _connector='OR'), name='discovery_genrecategory_bpm_range'),
        ),
        migrations.AddConstraint(
            model_name='genretag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bpm_max__isnull', True), ('bpm_min__isnull', True)), models.Q(('bpm_max__gte', models.F('bpm_min')), ('bpm_max__isnull', False), ('bpm_min__gt', 0), ('bpm_min__isnull', False)), _connector='OR'), name='discovery_genretag_bpm_range'),
        ),
    ]
