# Generated by Django 5.2.17 on 2026-09-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_remove_genrecategory_discovery_genrecategory_bpm_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='demo_poster',
            field=models.CharField(blank=True, default='', help_text='Bundled event poster path.', max_length=120),
        ),
    ]
