# Copyright © 2026 Xander Chen. All rights reserved.
# Generated by Django 5.2.17 on 2026-10-01 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_event_demo_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('official_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('photo', models.CharField(help_text='Bundled static image path.', max_length=160)),
                ('photo_credit', models.CharField(max_length=200)),
                ('photo_source_url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('photo_license', models.CharField(max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='djs', to='discovery.genrecategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
