# Generated by Django 5.2.17 on 2026-10-01 08:21

import discovery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_djprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Uploaded event poster; overrides bundled demo artwork.', upload_to=discovery.models.event_poster_path),
        ),
    ]
