# Generated by Django 5.2.17 on 2026-10-01 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_event_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djprofile',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'artist / DJ profile', 'verbose_name_plural': 'artist / DJ profiles'},
        ),
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='events', to='discovery.djprofile'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='official_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='photo',
            field=models.CharField(blank=True, help_text='Optional bundled static image path.', max_length=160),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='photo_license',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='photo_source_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
