# Generated by Django 5.2.17 on 2026-10-01 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_alter_djprofile_options_event_performers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('kind', models.CharField(choices=[('track', 'Track'), ('set', 'Set')], max_length=5)),
                ('platform', models.CharField(choices=[('soundcloud', 'SoundCloud'), ('youtube', 'YouTube')], max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='discovery.djprofile')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('dj', 'url'), name='dj_media_unique_url')],
            },
        ),
    ]
