# Generated by Django 5.2.17 on 2026-10-01 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_djmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='djprofile',
            name='active_since',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='labels',
            field=models.CharField(blank=True, help_text='Main labels, separated by commas.', max_length=200),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='origin',
            field=models.CharField(blank=True, help_text='Hometown and country, for example Ghent, Belgium.', max_length=120),
        ),
        migrations.CreateModel(
            name='DJSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify')], max_length=10)),
                ('url', models.URLField(max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='discovery.djprofile')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('dj', 'platform'), name='dj_social_one_per_platform')],
            },
        ),
    ]
