# Copyright © 2026 Xander Chen. All rights reserved.
# Generated by Django 5.2.17 on 2026-09-27 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('event_change', 'Event change'), ('group_offer', 'Group offer')], max_length=12)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='discovery.eventchange')),
                ('join_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='groups.joinrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='notification_inbox_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event_change__isnull', False), ('join_request__isnull', True), ('kind', 'event_change')), models.Q(('event_change__isnull', True), ('join_request__isnull', False), ('kind', 'group_offer')), _connector='OR'), name='notification_source_matches_kind'), models.UniqueConstraint(fields=('recipient', 'event_change'), name='notification_event_once'), models.UniqueConstraint(fields=('recipient', 'join_request'), name='notification_offer_once')],
            },
        ),
    ]
