# Copyright © 2026 Xander Chen. All rights reserved.
# Generated by Django 5.2.17 on 2026-09-28 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_alter_genrecategory_options'),
        ('groups', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_source_matches_kind',
        ),
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='groups.attendancegroup'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('event_change', 'Event change'), ('group_offer', 'Group offer'), ('group_request', 'New group request'), ('group_rejected', 'Group request rejected'), ('member_removed', 'Removed from group'), ('member_banned', 'Banned from group'), ('owner_transfer', 'Group ownership transferred')], max_length=14),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_change__isnull', False), ('group__isnull', True), ('join_request__isnull', True), ('kind', 'event_change')), models.Q(('event_change__isnull', True), ('group__isnull', True), ('join_request__isnull', False), ('kind__in', ['group_offer', 'group_request', 'group_rejected'])), models.Q(('event_change__isnull', True), ('group__isnull', False), ('join_request__isnull', True), ('kind__in', ['member_removed', 'member_banned', 'owner_transfer'])), _connector='OR'), name='notification_source_matches_kind'),
        ),
    ]
